const LABELS: Record<string, string> = {
  ACCEPTED: '已接受',
  ACTIVE: '进行中',
  APPROVED: '已批准',
  ARCHIVED: '已归档',
  BOTH: '罚款并计入返工成本',
  CANCELLED: '已取消',
  CHANGE_PENDING: '待图纸变更',
  CLOSED: '已关闭',
  COMPLETED: '已完成',
  CONDITIONAL: '有条件通过',
  CONDITIONAL_PASS: '有条件通过',
  CONFIRMED: '已确认',
  CONSTRUCTION_ORGANIZATION: '施工组织设计',
  CRITICAL: '严重',
  DEFECT_LIABILITY: '缺陷责任期',
  DRAFT: '草稿',
  FINAL_ACCEPTANCE_APPROVED: '竣工验收已批准',
  FINAL_ACCEPTANCE_PENDING: '待竣工验收',
  FINAL_SETTLEMENT_BOUND: '最终结算已绑定',
  FINE: '罚款',
  GENERAL: '一般方案',
  HIGH: '高',
  INITIATED: '已发起',
  IN_PROGRESS: '进行中',
  INTERNAL: '内部责任',
  LAGGING: '滞后',
  LOW: '低',
  MEDIUM: '中',
  METHOD_STATEMENT: '施工方法',
  MONTHLY: '每月',
  NONE: '无',
  NORMAL: '普通',
  OPEN: '待处理',
  OVERDUE: '逾期',
  PARTNER: '合作方责任',
  PASS: '通过',
  PASSED: '已通过',
  PENDING: '待处理',
  PENDING_REINSPECTION: '待复检',
  PENDING_VERIFICATION: '待验证',
  POSTED: '已登记',
  QUALITY: '质量',
  READY_TO_CLOSE: '待关闭',
  RECEIVED: '已接收',
  RECORDED: '已记录',
  REGULAR: '工程款',
  RETENTION: '质保金',
  RECTIFYING: '整改中',
  REJECT: '驳回',
  REJECTED: '已驳回',
  RELEASED: '已释放',
  RESPONDED: '已回复',
  REVISION: '修订计划',
  REWORK_COST: '计入返工成本',
  RFI_PENDING: '待发起 RFI',
  SAFETY: '安全',
  SECTION_ACCEPTANCE: '分项验收中',
  SINGLE: '单次',
  SPECIAL: '专项方案',
  SUBMITTED: '已提交',
  TAIL_PAYMENT_COLLECTED: '尾款已收取',
  UNDER_REVIEW: '审核中',
  URGENT: '紧急',
  WARRANTY_ACTIVE: '质保期',
  WARRANTY_RELEASED: '质保已释放',
  WEEKLY: '每周',
}

export function deliveryLabel(value?: string | null): string {
  if (!value) return '—'
  return LABELS[value] ?? value
}
