export const designTokens = {
  color: {
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    primaryActive: '#1e40af',
    info: '#0ea5e9',
    success: '#16a34a',
    warning: '#d97706',
    error: '#ef4444',
    text: '#152033',
    textSecondary: '#5f6f86',
    textTertiary: '#667085',
    textQuaternary: '#c5cfdd',
    border: '#e5ebf3',
    borderSecondary: '#edf1f7',
    borderStrong: '#cbd5e1',
    bgLayout: '#f6f8fb',
    bgContainer: '#ffffff',
    surfaceSubtle: '#f8fafc',
    surfaceTint: '#eef4ff',
    rowHover: '#f4f8ff',
    primarySoft: '#eaf2ff',
    successSoft: '#eafaf0',
    warningSoft: '#fff7e8',
    errorSoft: '#fff0f0',
  },
  font: {
    family: "'PingFang SC', 'Microsoft YaHei', -apple-system, BlinkMacSystemFont, sans-serif",
    sizeXs: 12,
    sizeSm: 13,
    sizeBase: 14,
    sizeLg: 16,
    sizeXl: 18,
    sizeXxl: 24,
    weightStrong: 700,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    full: 999,
  },
  control: {
    height: 34,
    compactTarget: 32,
  },
  shadow: {
    soft: '0 10px 30px rgba(21, 32, 51, 0.05)',
    sm: '0 6px 18px rgba(21, 32, 51, 0.045)',
    md: '0 18px 45px rgba(21, 32, 51, 0.08)',
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
  },
  shell: {
    sidebarWidth: 244,
    sidebarCollapsedWidth: 72,
    headerHeight: 68,
    bg: 'linear-gradient(180deg, rgba(234, 242, 255, 0.78), rgba(246, 248, 251, 0) 280px), #f6f8fb',
    sidebarBg: 'rgba(255, 255, 255, 0.94)',
    topbarBg: 'rgba(255, 255, 255, 0.82)',
    userHoverBg: 'rgba(255, 255, 255, 0.74)',
    maskBg: 'rgba(15, 23, 42, 0.34)',
    shadowSidebar: '8px 0 28px rgba(21, 32, 51, 0.04)',
    shadowLogo: '0 10px 22px rgba(37, 99, 235, 0.18)',
    shadowMobileSidebar: '10px 0 30px rgba(15, 23, 42, 0.16)',
  },
  brand: {
    logoGradient: 'linear-gradient(135deg, #2563eb, #14b8a6)',
    avatarGradient: 'linear-gradient(135deg, #2563eb, #0f766e)',
    logoForeground: '#ffffff',
  },
} as const

export const chartPalette = {
  categorical: [
    designTokens.color.primary,
    designTokens.color.info,
    designTokens.color.warning,
    designTokens.color.success,
    designTokens.color.error,
  ],
  extended: [
    designTokens.color.primary,
    designTokens.color.info,
    designTokens.color.warning,
    designTokens.color.success,
    designTokens.color.error,
    '#6366f1',
    '#a855f7',
    '#d946ef',
  ],
  semantic: {
    positive: designTokens.color.success,
    negative: designTokens.color.error,
    neutral: designTokens.color.textSecondary,
  },
  shadow: {
    emphasis: 'rgba(21, 32, 51, 0.15)',
  },
} as const

export const rootCssVariables = {
  '--primary': designTokens.color.primary,
  '--primary-hover': designTokens.color.primaryHover,
  '--primary-active': designTokens.color.primaryActive,
  '--bg': designTokens.color.bgLayout,
  '--surface': designTokens.color.bgContainer,
  '--surface-subtle': designTokens.color.surfaceSubtle,
  '--surface-tint': designTokens.color.surfaceTint,
  '--border': designTokens.color.border,
  '--border-subtle': designTokens.color.borderSecondary,
  '--border-strong': designTokens.color.borderStrong,
  '--text': designTokens.color.text,
  '--text-secondary': designTokens.color.textSecondary,
  '--muted': designTokens.color.textTertiary,
  '--disabled': designTokens.color.textQuaternary,
  '--success': designTokens.color.success,
  '--warning': designTokens.color.warning,
  '--error': designTokens.color.error,
  '--info': designTokens.color.info,
  '--radius-sm': `${designTokens.radius.sm}px`,
  '--radius-md': `${designTokens.radius.md}px`,
  '--radius-lg': `${designTokens.radius.lg}px`,
  '--radius-full': `${designTokens.radius.full}px`,
  '--shell-sidebar-width': `${designTokens.shell.sidebarWidth}px`,
  '--shell-sidebar-collapsed-width': `${designTokens.shell.sidebarCollapsedWidth}px`,
  '--shell-header-height': `${designTokens.shell.headerHeight}px`,
  '--shell-bg': designTokens.shell.bg,
  '--shell-sidebar-bg': designTokens.shell.sidebarBg,
  '--shell-topbar-bg': designTokens.shell.topbarBg,
  '--shell-user-hover-bg': designTokens.shell.userHoverBg,
  '--shell-mask-bg': designTokens.shell.maskBg,
  '--shell-shadow-sidebar': designTokens.shell.shadowSidebar,
  '--shell-shadow-logo': designTokens.shell.shadowLogo,
  '--shell-shadow-mobile-sidebar': designTokens.shell.shadowMobileSidebar,
  '--shadow-soft': designTokens.shadow.soft,
  '--shadow-sm': designTokens.shadow.sm,
  '--shadow-md': designTokens.shadow.md,
  '--primary-soft': designTokens.color.primarySoft,
  '--success-soft': designTokens.color.successSoft,
  '--warning-soft': designTokens.color.warningSoft,
  '--error-soft': designTokens.color.errorSoft,
  '--brand-gradient-logo': designTokens.brand.logoGradient,
  '--brand-gradient-avatar': designTokens.brand.avatarGradient,
  '--brand-logo-fg': designTokens.brand.logoForeground,
  '--font-family': designTokens.font.family,
  '--font-size-xs': `${designTokens.font.sizeXs}px`,
  '--font-size-sm': `${designTokens.font.sizeSm}px`,
  '--font-size-base': `${designTokens.font.sizeBase}px`,
  '--font-size-lg': `${designTokens.font.sizeLg}px`,
  '--font-size-xl': `${designTokens.font.sizeXl}px`,
  '--font-size-xxl': `${designTokens.font.sizeXxl}px`,
  '--spacing-xs': `${designTokens.spacing.xs}px`,
  '--spacing-sm': `${designTokens.spacing.sm}px`,
  '--spacing-md': `${designTokens.spacing.md}px`,
  '--spacing-lg': `${designTokens.spacing.lg}px`,
  '--control-compact-target': `${designTokens.control.compactTarget}px`,
} as const

export const antdTheme = {
  token: {
    colorPrimary: designTokens.color.primary,
    colorInfo: designTokens.color.info,
    colorSuccess: designTokens.color.success,
    colorWarning: designTokens.color.warning,
    colorError: designTokens.color.error,
    colorText: designTokens.color.text,
    colorTextSecondary: designTokens.color.textSecondary,
    colorTextTertiary: designTokens.color.textTertiary,
    colorTextQuaternary: designTokens.color.textQuaternary,
    colorBorder: designTokens.color.border,
    colorBorderSecondary: designTokens.color.borderSecondary,
    colorBgLayout: designTokens.color.bgLayout,
    colorBgContainer: designTokens.color.bgContainer,
    colorBgElevated: designTokens.color.bgContainer,
    fontFamily: designTokens.font.family,
    fontSize: designTokens.font.sizeBase,
    fontSizeSM: designTokens.font.sizeSm,
    fontSizeLG: designTokens.font.sizeLg,
    fontSizeXL: designTokens.font.sizeXl,
    fontWeightStrong: designTokens.font.weightStrong,
    borderRadius: designTokens.radius.sm,
    controlHeight: designTokens.control.height,
  },
  components: {
    Button: {
      colorText: designTokens.color.text,
      colorPrimary: designTokens.color.primary,
      colorPrimaryHover: designTokens.color.primaryHover,
      colorPrimaryActive: designTokens.color.primaryActive,
      borderRadius: designTokens.radius.sm,
      controlHeight: designTokens.control.height,
    },
    Input: {
      borderRadius: designTokens.radius.sm,
      controlHeight: designTokens.control.height,
    },
    Select: {
      borderRadius: designTokens.radius.sm,
      controlHeight: designTokens.control.height,
    },
    Table: {
      headerBg: designTokens.color.surfaceSubtle,
      headerColor: designTokens.color.textSecondary,
      colorText: designTokens.color.text,
      rowHoverBg: designTokens.color.rowHover,
      borderColor: designTokens.color.border,
      fontSize: designTokens.font.sizeBase,
      headerSplitColor: designTokens.color.borderSecondary,
    },
    Tabs: {
      itemColor: designTokens.color.textSecondary,
      itemSelectedColor: designTokens.color.primary,
      itemHoverColor: designTokens.color.primary,
      inkBarColor: designTokens.color.primary,
    },
    Card: {
      colorTextHeading: designTokens.color.text,
      fontSize: designTokens.font.sizeBase,
      headerFontSize: 15,
    },
    Modal: {
      titleFontSize: designTokens.font.sizeLg,
    },
    Drawer: {
      fontSizeLG: designTokens.font.sizeLg,
    },
    Form: {
      labelColor: designTokens.color.textSecondary,
      fontSize: designTokens.font.sizeBase,
    },
  },
} as const

export function applyRootCssVariables(root: HTMLElement = document.documentElement) {
  Object.entries(rootCssVariables).forEach(([name, value]) => {
    root.style.setProperty(name, value)
  })
}
