import type { RouteRecordRaw } from 'vue-router'
import {
  AccountPage,
  BidTenderDetailPage,
  ContractCreatePage,
  ContractDetailPage,
  ContractEditPage,
  CostTargetPage,
  PartnerDetailPage,
  ProjectEditPage,
  ProjectMembersPage,
  ProjectOverviewPage,
  SchedulePage,
  SettlementWorkspacePage,
  SupplierSourcingPage,
  WorkflowWorkbenchPage,
} from './components'

export const contextRoutes: RouteRecordRaw[] = [
  {
    path: '/supplier-sourcing',
    name: 'LegacySupplierSourcing',
    component: SupplierSourcingPage,
    meta: { shell: true, permission: 'supplier:sourcing:query' },
  },
  {
    path: '/bid-cost',
    name: 'LegacyBidCostRedirect',
    redirect: (to) => ({ path: '/engineering-tender/records', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'bid:query' },
  },
  {
    path: '/engineering-tender/records/:id',
    name: 'EngineeringTenderDetail',
    component: BidTenderDetailPage,
    meta: { shell: true, permission: 'bid:query' },
  },
  {
    path: '/system',
    name: 'V2SystemRedirect',
    redirect: (to) => ({ path: '/system/dict', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'system:dict:list', adminOnly: true },
  },
  {
    path: '/profile',
    name: 'V2Profile',
    component: AccountPage,
    meta: { shell: true },
  },
  {
    path: '/settings',
    name: 'V2Settings',
    component: AccountPage,
    meta: { shell: true },
  },
  {
    path: '/help',
    name: 'V2Help',
    component: AccountPage,
    meta: { shell: true },
  },
  {
    path: '/material',
    name: 'V2MaterialRedirect',
    redirect: (to) => ({ path: '/material/dictionary', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'material:dict:list' },
  },
  {
    path: '/payment',
    name: 'V2PaymentRedirect',
    redirect: (to) => ({ path: '/payment/application', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'payment:app:query' },
  },
  {
    path: '/inventory',
    name: 'V2InventoryRedirect',
    redirect: (to) => ({ path: '/inventory/warehouse', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'inventory:warehouse:list' },
  },
  {
    path: '/inventory/transaction',
    name: 'V2InventoryTransactionRedirect',
    redirect: (to) => ({ path: '/inventory/stock', query: to.query, hash: '#transactions' }),
    meta: { shell: true, permission: 'inventory:transaction:list' },
  },
  {
    path: '/purchase',
    name: 'V2PurchaseRedirect',
    redirect: (to) => ({ path: '/purchase/order', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'purchase:order:query' },
  },
  {
    path: '/subcontract',
    name: 'V2SubcontractRedirect',
    redirect: (to) => ({ path: '/subcontract/task', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'subtask:query' },
  },
  {
    path: '/settlement',
    name: 'V2SettlementRedirect',
    redirect: (to) => ({ path: '/settlement/list', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'settlement:query' },
  },
  {
    path: '/project',
    name: 'V2ProjectRedirect',
    redirect: (to) => ({ path: '/project/list', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'project:query' },
  },
  {
    path: '/alert',
    name: 'V2LegacyAlertRedirect',
    redirect: (to) => ({ path: '/dashboard', query: to.query, hash: '#risk-list' }),
    meta: { shell: true, permission: 'alert:view' },
  },
  {
    path: '/approval',
    name: 'V2LegacyApprovalRedirect',
    redirect: (to) => ({ path: '/approval/todo', query: to.query }),
    meta: { shell: true },
  },
  {
    path: '/approval/instances/:instanceId',
    name: 'V2WorkflowInstanceDetail',
    component: WorkflowWorkbenchPage,
    meta: { shell: true, workflowTab: 'todo' },
  },
  {
    path: '/approval/:instanceId',
    name: 'V2LegacyApprovalDetailRedirect',
    redirect: (to) => ({
      path: `/approval/instances/${String(to.params.instanceId)}`,
      query: to.query,
    }),
    meta: { shell: true },
  },
  {
    path: '/project-schedule/:scheduleId',
    name: 'V2ShellProjectScheduleDetail',
    component: SchedulePage,
    meta: {
      shell: true,
      permission: 'schedule:query',
    },
  },
  {
    path: '/project/:projectId/overview',
    name: 'V2ShellProjectOverview',
    component: ProjectOverviewPage,
    meta: { shell: true, permission: 'project:query' },
  },
  {
    path: '/project/:projectId/members',
    name: 'V2ShellProjectMembers',
    component: ProjectMembersPage,
    meta: { shell: true, permission: 'project:member:list' },
  },
  {
    path: '/project/:projectId/edit',
    name: 'V2ShellProjectEdit',
    component: ProjectEditPage,
    meta: { shell: true, permission: 'project:edit' },
  },
  {
    path: '/partner/:id',
    name: 'V2ShellPartnerDetail',
    component: PartnerDetailPage,
    meta: { shell: true, permission: 'partner:query' },
  },
  {
    path: '/contract',
    name: 'V2ContractRootRedirect',
    redirect: (to) => ({ path: '/contract/ledger', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'contract:query' },
  },
  {
    path: '/variation',
    name: 'V2VariationRootRedirect',
    redirect: (to) => ({ path: '/variation/order', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'variation:order:query' },
  },
  {
    path: '/cost',
    name: 'V2CostRootRedirect',
    redirect: (to) => ({ path: '/cost/ledger', query: to.query, hash: to.hash }),
    meta: { shell: true, permission: 'cost:ledger:query' },
  },
  {
    path: '/cost/subject',
    name: 'V2CostSubjectRootRedirect',
    redirect: (to) => ({
      path: '/cost/subject/taxonomy',
      query: to.query,
      hash: to.hash,
    }),
    meta: { shell: true, permission: 'cost:query' },
  },
  {
    path: '/cost-target',
    name: 'V2CostTargetRootRedirect',
    redirect: (to) => ({
      path: '/cost-budget',
      query: to.query,
      hash: to.hash,
    }),
    meta: { shell: true, permission: 'cost:target:query' },
  },
  {
    path: '/cost-target/index',
    name: 'V2CostTargetIndexRedirect',
    redirect: (to) => ({
      path: '/cost-budget',
      query: to.query,
      hash: to.hash,
    }),
    meta: { shell: true, permission: 'cost:target:query' },
  },
  {
    path: '/budget',
    name: 'V2BudgetRedirect',
    redirect: (to) => ({
      path: '/cost-budget',
      query: to.query,
      hash: to.hash,
    }),
    meta: { shell: true, permission: 'cost:target:query' },
  },
  {
    path: '/cost-target/create',
    name: 'V2ShellCostTargetCreate',
    component: CostTargetPage,
    meta: {
      shell: true,
      permission: 'cost:target:add',
    },
  },
  {
    path: '/cost-target/:id/edit',
    name: 'V2ShellCostTargetEdit',
    component: CostTargetPage,
    meta: {
      shell: true,
      permission: 'cost:target:edit',
    },
  },
  {
    path: '/contract/create',
    name: 'V2ShellContractCreate',
    component: ContractCreatePage,
    meta: { shell: true, permission: 'contract:add' },
  },
  {
    path: '/contract/:id',
    name: 'V2ShellContractDetail',
    component: ContractDetailPage,
    meta: { shell: true, permission: 'contract:query' },
  },
  {
    path: '/contract/:id/edit',
    name: 'V2ShellContractEdit',
    component: ContractEditPage,
    meta: { shell: true, permission: 'contract:edit' },
  },
  {
    path: '/settlement/:id',
    name: 'V2ShellSettlementDetail',
    component: SettlementWorkspacePage,
    meta: { shell: true, permission: 'settlement:query' },
  },
]
