-- Normalize internal demo business numbers after all seed stages.
-- External transaction, voucher and invoice numbers intentionally remain unchanged.

DROP TEMPORARY TABLE IF EXISTS tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('XM-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM pm_project;
UPDATE pm_project t JOIN tmp_business_codes n ON n.id=t.id SET t.project_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('PTN-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM md_partner;
UPDATE md_partner t JOIN tmp_business_codes n ON n.id=t.id SET t.partner_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('CT-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM ct_contract;
UPDATE ct_contract t JOIN tmp_business_codes n ON n.id=t.id SET t.contract_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('CC-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM ct_contract_change;
UPDATE ct_contract_change t JOIN tmp_business_codes n ON n.id=t.id SET t.change_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('VO-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM var_order;
UPDATE var_order t JOIN tmp_business_codes n ON n.id=t.id SET t.var_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('PR-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM mat_purchase_request;
UPDATE mat_purchase_request t JOIN tmp_business_codes n ON n.id=t.id SET t.request_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('PO-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM mat_purchase_order;
UPDATE mat_purchase_order t JOIN tmp_business_codes n ON n.id=t.id SET t.order_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('MR-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM mat_receipt;
UPDATE mat_receipt t JOIN tmp_business_codes n ON n.id=t.id SET t.receipt_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('REQ-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM mat_requisition;
UPDATE mat_requisition t JOIN tmp_business_codes n ON n.id=t.id SET t.requisition_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('MRT-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM mat_material_return;
UPDATE mat_material_return t JOIN tmp_business_codes n ON n.id=t.id SET t.return_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('SRT-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM sp_supplier_return;
UPDATE sp_supplier_return t JOIN tmp_business_codes n ON n.id=t.id SET t.return_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('SUB-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM sub_task;
UPDATE sub_task t JOIN tmp_business_codes n ON n.id=t.id SET t.task_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('SM-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM sub_measure;
UPDATE sub_measure t JOIN tmp_business_codes n ON n.id=t.id SET t.measure_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('PAY-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM pay_application;
UPDATE pay_application t JOIN tmp_business_codes n ON n.id=t.id SET t.apply_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('PMT-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM pay_record;
UPDATE pay_record t JOIN tmp_business_codes n ON n.id=t.id SET t.record_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('STL-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM stl_settlement;
UPDATE stl_settlement t JOIN tmp_business_codes n ON n.id=t.id SET t.settlement_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('EXP-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM expense_application;
UPDATE expense_application t JOIN tmp_business_codes n ON n.id=t.id SET t.expense_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('RV-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM contract_revenue;
UPDATE contract_revenue t JOIN tmp_business_codes n ON n.id=t.id SET t.revenue_code=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('CJ-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM cash_journal_entry;
UPDATE cash_journal_entry t JOIN tmp_business_codes n ON n.id=t.id SET t.entry_no=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
CREATE TEMPORARY TABLE tmp_business_codes AS SELECT id, CONCAT('DOC-', DATE_FORMAT(created_at,'%Y%m%d'), '-', LPAD(ROW_NUMBER() OVER (PARTITION BY tenant_id, DATE(created_at) ORDER BY id),3,'0')) new_code FROM biz_document_generation;
UPDATE biz_document_generation t JOIN tmp_business_codes n ON n.id=t.id SET t.generation_no=n.new_code;
DROP TEMPORARY TABLE tmp_business_codes;
