-- 项目资金闭环：项目预算、预算科目、不可变预算台账、合同预算分配。
CREATE TABLE project_budget (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    version_no VARCHAR(32) NOT NULL,
    budget_name VARCHAR(200) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    approval_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    active_flag TINYINT NOT NULL DEFAULT 0,
    active_token BIGINT NULL COMMENT '激活时等于project_id，用于数据库保证单项目唯一生效版本',
    effective_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_project_budget_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    UNIQUE KEY uk_project_budget_version (tenant_id, project_id, version_no, deleted_flag),
    UNIQUE KEY uk_project_budget_active (tenant_id, active_token),
    KEY idx_project_budget_project_status (tenant_id, project_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='项目预算版本';

CREATE TABLE project_budget_line (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    budget_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    cost_subject_id BIGINT NOT NULL,
    budget_amount DECIMAL(18,2) NOT NULL,
    reserved_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    consumed_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_budget_line_budget FOREIGN KEY (budget_id) REFERENCES project_budget(id) ON DELETE RESTRICT,
    CONSTRAINT fk_budget_line_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_budget_line_subject FOREIGN KEY (cost_subject_id) REFERENCES cost_subject(id) ON DELETE RESTRICT,
    UNIQUE KEY uk_budget_line_subject (tenant_id, budget_id, cost_subject_id, deleted_flag),
    KEY idx_budget_line_project_subject (tenant_id, project_id, cost_subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='项目预算科目';

CREATE TABLE budget_ledger (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    budget_id BIGINT NOT NULL,
    budget_line_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_id BIGINT NOT NULL,
    entry_type VARCHAR(32) NOT NULL COMMENT 'RESERVE/RELEASE/CONSUME/REVERSE/ADJUST',
    amount DECIMAL(18,2) NOT NULL,
    reserved_balance DECIMAL(18,2) NOT NULL,
    consumed_balance DECIMAL(18,2) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_budget_ledger_budget FOREIGN KEY (budget_id) REFERENCES project_budget(id) ON DELETE RESTRICT,
    CONSTRAINT fk_budget_ledger_line FOREIGN KEY (budget_line_id) REFERENCES project_budget_line(id) ON DELETE RESTRICT,
    CONSTRAINT fk_budget_ledger_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    UNIQUE KEY uk_budget_ledger_idempotency (tenant_id, idempotency_key),
    KEY idx_budget_ledger_business (tenant_id, business_type, business_id),
    KEY idx_budget_ledger_line_time (tenant_id, budget_line_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不可变预算占用与消耗台账';

CREATE TABLE contract_budget_allocation (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    budget_line_id BIGINT NOT NULL,
    allocated_amount DECIMAL(18,2) NOT NULL,
    reserved_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    consumed_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_contract_budget_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_contract_budget_contract FOREIGN KEY (contract_id) REFERENCES ct_contract(id) ON DELETE RESTRICT,
    CONSTRAINT fk_contract_budget_line FOREIGN KEY (budget_line_id) REFERENCES project_budget_line(id) ON DELETE RESTRICT,
    UNIQUE KEY uk_contract_budget_line (tenant_id, contract_id, budget_line_id, deleted_flag),
    KEY idx_contract_budget_project (tenant_id, project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合同预算科目分配';
