CREATE TABLE project_schedule_plan (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    plan_code VARCHAR(64) NOT NULL,
    plan_name VARCHAR(200) NOT NULL,
    plan_type VARCHAR(20) NOT NULL DEFAULT 'BASELINE',
    version_no INT NOT NULL,
    parent_plan_id BIGINT NULL,
    corrective_action_id BIGINT NULL,
    planned_start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    approval_instance_id BIGINT NULL,
    activated_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_schedule_code (tenant_id, project_id, plan_code, deleted_flag),
    UNIQUE KEY uk_project_schedule_version (tenant_id, project_id, version_no, deleted_flag),
    KEY idx_project_schedule_active (tenant_id, project_id, status),
    CONSTRAINT fk_project_schedule_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_schedule_parent FOREIGN KEY (parent_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_schedule_approval FOREIGN KEY (approval_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_schedule_dates CHECK (planned_start_date <= planned_end_date),
    CONSTRAINT ck_project_schedule_type CHECK (plan_type IN ('BASELINE','REVISION')),
    CONSTRAINT ck_project_schedule_status CHECK (status IN ('DRAFT','PENDING','ACTIVE','REJECTED','SUPERSEDED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE project_wbs_task (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    schedule_plan_id BIGINT NOT NULL,
    parent_task_id BIGINT NULL,
    predecessor_task_id BIGINT NULL,
    task_code VARCHAR(64) NOT NULL,
    task_name VARCHAR(200) NOT NULL,
    work_area VARCHAR(200) NULL,
    responsible_user_id BIGINT NULL,
    planned_start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    weight_percent DECIMAL(7,4) NOT NULL,
    planned_quantity DECIMAL(18,4) NULL,
    unit VARCHAR(30) NULL,
    actual_start_date DATE NULL,
    actual_end_date DATE NULL,
    actual_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    actual_progress DECIMAL(7,4) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    sort_order INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_wbs_code (tenant_id, schedule_plan_id, task_code, deleted_flag),
    KEY idx_project_wbs_project_date (tenant_id, project_id, planned_start_date, planned_end_date),
    CONSTRAINT fk_project_wbs_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_wbs_schedule FOREIGN KEY (schedule_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_wbs_parent FOREIGN KEY (parent_task_id) REFERENCES project_wbs_task(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_wbs_predecessor FOREIGN KEY (predecessor_task_id) REFERENCES project_wbs_task(id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_wbs_dates CHECK (planned_start_date <= planned_end_date),
    CONSTRAINT ck_project_wbs_weight CHECK (weight_percent > 0 AND weight_percent <= 100),
    CONSTRAINT ck_project_wbs_progress CHECK (actual_progress >= 0 AND actual_progress <= 100 AND actual_quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE project_period_plan (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    schedule_plan_id BIGINT NOT NULL,
    parent_period_plan_id BIGINT NULL,
    period_type VARCHAR(20) NOT NULL,
    period_code VARCHAR(64) NOT NULL,
    period_name VARCHAR(200) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    approval_instance_id BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_period_code (tenant_id, project_id, period_code, deleted_flag),
    KEY idx_project_period_date (tenant_id, project_id, period_type, start_date, end_date, status),
    CONSTRAINT fk_project_period_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_period_schedule FOREIGN KEY (schedule_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_period_parent FOREIGN KEY (parent_period_plan_id) REFERENCES project_period_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_period_approval FOREIGN KEY (approval_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_period_dates CHECK (start_date <= end_date),
    CONSTRAINT ck_project_period_type CHECK (period_type IN ('MONTHLY','WEEKLY')),
    CONSTRAINT ck_project_period_status CHECK (status IN ('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE project_period_plan_item (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    period_plan_id BIGINT NOT NULL,
    wbs_task_id BIGINT NOT NULL,
    target_progress DECIMAL(7,4) NOT NULL,
    planned_quantity DECIMAL(18,4) NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_period_item (tenant_id, period_plan_id, wbs_task_id),
    CONSTRAINT fk_project_period_item_plan FOREIGN KEY (period_plan_id) REFERENCES project_period_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_period_item_task FOREIGN KEY (wbs_task_id) REFERENCES project_wbs_task(id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_period_item_progress CHECK (target_progress >= 0 AND target_progress <= 100 AND (planned_quantity IS NULL OR planned_quantity >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE site_daily_progress (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    daily_log_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    schedule_plan_id BIGINT NOT NULL,
    weekly_plan_id BIGINT NOT NULL,
    wbs_task_id BIGINT NOT NULL,
    previous_progress DECIMAL(7,4) NOT NULL,
    current_progress DECIMAL(7,4) NOT NULL,
    completed_quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
    work_description VARCHAR(500) NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_site_daily_progress (tenant_id, daily_log_id, wbs_task_id),
    KEY idx_site_daily_progress_task (tenant_id, wbs_task_id, daily_log_id),
    CONSTRAINT fk_site_daily_progress_log FOREIGN KEY (daily_log_id) REFERENCES site_daily_log(id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_daily_progress_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_daily_progress_schedule FOREIGN KEY (schedule_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_daily_progress_week FOREIGN KEY (weekly_plan_id) REFERENCES project_period_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_daily_progress_task FOREIGN KEY (wbs_task_id) REFERENCES project_wbs_task(id) ON DELETE RESTRICT,
    CONSTRAINT ck_site_daily_progress_value CHECK (previous_progress >= 0 AND current_progress >= previous_progress AND current_progress <= 100 AND completed_quantity >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE project_progress_snapshot (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    schedule_plan_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    source_daily_log_id BIGINT NULL,
    planned_progress DECIMAL(7,4) NOT NULL,
    actual_progress DECIMAL(7,4) NOT NULL,
    deviation_percent DECIMAL(7,4) NOT NULL,
    lagging_task_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    formula_version VARCHAR(40) NOT NULL DEFAULT 'SCHEDULE_PROGRESS_V1',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_progress_snapshot (tenant_id, schedule_plan_id, snapshot_date),
    CONSTRAINT fk_project_snapshot_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_snapshot_schedule FOREIGN KEY (schedule_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_snapshot_log FOREIGN KEY (source_daily_log_id) REFERENCES site_daily_log(id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_snapshot_progress CHECK (planned_progress >= 0 AND planned_progress <= 100 AND actual_progress >= 0 AND actual_progress <= 100),
    CONSTRAINT ck_project_snapshot_status CHECK (status IN ('ON_TRACK','LAGGING','OVERDUE','COMPLETED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE project_corrective_action (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    schedule_plan_id BIGINT NOT NULL,
    snapshot_id BIGINT NOT NULL,
    alert_id BIGINT NULL,
    action_code VARCHAR(64) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    action_plan VARCHAR(1000) NOT NULL,
    responsible_user_id BIGINT NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    approval_instance_id BIGINT NULL,
    generated_revision_plan_id BIGINT NULL,
    completed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_corrective_code (tenant_id, project_id, action_code, deleted_flag),
    UNIQUE KEY uk_project_corrective_snapshot (tenant_id, snapshot_id, deleted_flag),
    CONSTRAINT fk_project_corrective_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_corrective_schedule FOREIGN KEY (schedule_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_corrective_snapshot FOREIGN KEY (snapshot_id) REFERENCES project_progress_snapshot(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_corrective_alert FOREIGN KEY (alert_id) REFERENCES alert_log(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_corrective_approval FOREIGN KEY (approval_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_corrective_revision FOREIGN KEY (generated_revision_plan_id) REFERENCES project_schedule_plan(id) ON DELETE RESTRICT,
    CONSTRAINT ck_project_corrective_status CHECK (status IN ('DRAFT','PENDING','APPROVED','REJECTED','COMPLETED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE project_schedule_plan
    ADD CONSTRAINT fk_project_schedule_corrective FOREIGN KEY (corrective_action_id) REFERENCES project_corrective_action(id) ON DELETE RESTRICT;

INSERT IGNORE INTO wf_template(id,tenant_id,template_code,template_name,business_type,enabled,created_by,remark) VALUES
(50033,0,'TPL-PROJECT-SCHEDULE-001','项目基线与修订计划审批','PROJECT_SCHEDULE',1,1,'项目计划闭环：项目经理、工程经理、分管领导三级审批'),
(50034,0,'TPL-PROJECT-PERIOD-PLAN-001','项目月周计划审批','PROJECT_PERIOD_PLAN',1,1,'项目计划闭环：项目经理、工程经理两级审批'),
(50035,0,'TPL-PROJECT-CORRECTIVE-001','项目进度纠偏审批','PROJECT_CORRECTIVE_ACTION',1,1,'项目计划闭环：项目经理、工程经理、分管领导三级审批');

INSERT IGNORE INTO wf_template_node(id,tenant_id,template_id,node_code,node_name,node_order,node_type,approve_mode,approver_config,allow_transfer,allow_add_sign,timeout_hours) VALUES
(53301,0,50033,'N1','项目经理审批',1,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53302,0,50033,'N2','工程经理审批',2,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53303,0,50033,'N3','分管领导审批',3,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,72),
(53401,0,50034,'N1','项目经理审批',1,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53402,0,50034,'N2','工程经理审批',2,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53501,0,50035,'N1','项目经理审批',1,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53502,0,50035,'N2','工程经理审批',2,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53503,0,50035,'N3','分管领导审批',3,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,72);

INSERT IGNORE INTO alert_rule_config(id,tenant_id,rule_type,alert_domain,alert_category,enabled,dedup_hours,threshold_ratio,severity_override,created_by,remark)
VALUES(185001,0,'PROJECT_PROGRESS_DELAY','SCHEDULE','PROGRESS_DELAY',1,24,0.0500,'HIGH',1,'计划实际偏差达到5个百分点时生成延期预警');

INSERT IGNORE INTO sys_menu(id,tenant_id,parent_id,menu_name,menu_type,path,component,perms,icon,order_num,status,visible) VALUES
(1085,0,2,'项目计划','MENU','project-schedule','project-schedule/index','schedule:query','schedule',8,'ENABLE',1),
(1086,0,1085,'维护项目计划','BUTTON',NULL,NULL,'schedule:maintain',NULL,1,'ENABLE',1),
(1087,0,1085,'提交计划审批','BUTTON',NULL,NULL,'schedule:submit',NULL,2,'ENABLE',1),
(1088,0,1085,'填报实际进度','BUTTON',NULL,NULL,'schedule:progress',NULL,3,'ENABLE',1),
(1089,0,1085,'发起纠偏审批','BUTTON',NULL,NULL,'schedule:correct',NULL,4,'ENABLE',1);

INSERT IGNORE INTO sys_role_menu(id,role_id,menu_id)
SELECT 185000000+r.id*10000+m.id,r.id,m.id FROM sys_role r JOIN sys_menu m ON m.id BETWEEN 1085 AND 1089
WHERE r.role_code IN ('SUPER_ADMIN','ADMIN','PROJECT_MANAGER','COST_MANAGER','AUDITOR') AND r.deleted_flag=0;
