SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE qs_inspection_plan (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    plan_code VARCHAR(64) NOT NULL,
    plan_name VARCHAR(200) NOT NULL,
    inspection_type VARCHAR(16) NOT NULL COMMENT 'QUALITY/SAFETY',
    frequency_type VARCHAR(16) NOT NULL COMMENT 'SINGLE/WEEKLY/MONTHLY',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    owner_user_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    activated_by BIGINT NULL,
    activated_at DATETIME NULL,
    completed_by BIGINT NULL,
    completed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_qs_plan_code (tenant_id, project_id, plan_code, deleted_flag),
    KEY idx_qs_plan_project_status (tenant_id, project_id, status, start_date),
    CONSTRAINT fk_qs_plan_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT ck_qs_plan_type CHECK (inspection_type IN ('QUALITY','SAFETY')),
    CONSTRAINT ck_qs_plan_frequency CHECK (frequency_type IN ('SINGLE','WEEKLY','MONTHLY')),
    CONSTRAINT ck_qs_plan_status CHECK (status IN ('DRAFT','ACTIVE','COMPLETED','CANCELLED')),
    CONSTRAINT ck_qs_plan_dates CHECK (end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='质量安全检查计划';

CREATE TABLE qs_inspection_record (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    plan_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    inspection_code VARCHAR(64) NOT NULL,
    inspection_date DATE NOT NULL,
    location VARCHAR(200) NOT NULL,
    inspector_user_id BIGINT NOT NULL,
    conclusion VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    summary VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    submitted_by BIGINT NULL,
    submitted_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_qs_inspection_code (tenant_id, project_id, inspection_code, deleted_flag),
    KEY idx_qs_inspection_plan (tenant_id, plan_id, inspection_date, status),
    CONSTRAINT fk_qs_inspection_plan FOREIGN KEY (plan_id) REFERENCES qs_inspection_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_inspection_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT ck_qs_inspection_conclusion CHECK (conclusion IN ('PENDING','PASS','ISSUES')),
    CONSTRAINT ck_qs_inspection_status CHECK (status IN ('DRAFT','SUBMITTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='质量安全检查记录';

CREATE TABLE qs_issue (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    plan_id BIGINT NOT NULL,
    inspection_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    issue_code VARCHAR(64) NOT NULL,
    issue_type VARCHAR(16) NOT NULL COMMENT 'QUALITY/SAFETY',
    category VARCHAR(100) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    responsible_kind VARCHAR(16) NOT NULL COMMENT 'INTERNAL/PARTNER',
    responsible_partner_id BIGINT NULL,
    responsible_user_id BIGINT NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    closed_by BIGINT NULL,
    closed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_qs_issue_code (tenant_id, project_id, issue_code, deleted_flag),
    KEY idx_qs_issue_record (tenant_id, inspection_id, status),
    KEY idx_qs_issue_responsible (tenant_id, responsible_user_id, due_date, status),
    KEY idx_qs_issue_partner (tenant_id, responsible_partner_id, status),
    CONSTRAINT fk_qs_issue_plan FOREIGN KEY (plan_id) REFERENCES qs_inspection_plan(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_issue_inspection FOREIGN KEY (inspection_id) REFERENCES qs_inspection_record(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_issue_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_issue_partner FOREIGN KEY (responsible_partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT ck_qs_issue_type CHECK (issue_type IN ('QUALITY','SAFETY')),
    CONSTRAINT ck_qs_issue_severity CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT ck_qs_issue_responsible CHECK ((responsible_kind='INTERNAL' AND responsible_partner_id IS NULL) OR (responsible_kind='PARTNER' AND responsible_partner_id IS NOT NULL)),
    CONSTRAINT ck_qs_issue_status CHECK (status IN ('OPEN','RECTIFYING','PENDING_REINSPECTION','CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='质量安全问题单';

CREATE TABLE qs_rectification (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    issue_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    round_no INT NOT NULL,
    action_description VARCHAR(2000) NOT NULL,
    responsible_user_id BIGINT NOT NULL,
    planned_complete_date DATE NOT NULL,
    actual_completed_at DATETIME NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    submitted_by BIGINT NULL,
    submitted_at DATETIME NULL,
    reinspection_comment VARCHAR(1000) NULL,
    reinspected_by BIGINT NULL,
    reinspected_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_qs_rectification_round (tenant_id, issue_id, round_no, deleted_flag),
    KEY idx_qs_rectification_issue (tenant_id, issue_id, status),
    CONSTRAINT fk_qs_rectification_issue FOREIGN KEY (issue_id) REFERENCES qs_issue(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_rectification_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT ck_qs_rectification_round CHECK (round_no > 0),
    CONSTRAINT ck_qs_rectification_status CHECK (status IN ('DRAFT','SUBMITTED','PASSED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='问题整改与复验轮次';

CREATE TABLE qs_consequence (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    issue_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    contract_id BIGINT NULL,
    consequence_code VARCHAR(64) NOT NULL,
    decision_type VARCHAR(20) NOT NULL COMMENT 'NONE/FINE/REWORK_COST/BOTH',
    fine_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    rework_cost_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    evaluation_score DECIMAL(5,2) NOT NULL,
    evaluation_comment VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    cost_item_id BIGINT NULL,
    evaluation_id BIGINT NULL,
    posted_by BIGINT NULL,
    posted_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_qs_consequence_issue (tenant_id, issue_id, deleted_flag),
    UNIQUE KEY uk_qs_consequence_code (tenant_id, project_id, consequence_code, deleted_flag),
    KEY idx_qs_consequence_partner (tenant_id, partner_id, status),
    CONSTRAINT fk_qs_consequence_issue FOREIGN KEY (issue_id) REFERENCES qs_issue(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_consequence_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_consequence_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_consequence_contract FOREIGN KEY (contract_id) REFERENCES ct_contract(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_consequence_cost FOREIGN KEY (cost_item_id) REFERENCES cost_item(id) ON DELETE RESTRICT,
    CONSTRAINT ck_qs_consequence_decision CHECK (decision_type IN ('NONE','FINE','REWORK_COST','BOTH')),
    CONSTRAINT ck_qs_consequence_amount CHECK (fine_amount >= 0 AND rework_cost_amount >= 0),
    CONSTRAINT ck_qs_consequence_score CHECK (evaluation_score >= 0 AND evaluation_score <= 100),
    CONSTRAINT ck_qs_consequence_status CHECK (status IN ('DRAFT','POSTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='问题处罚与成本后果';

CREATE TABLE qs_partner_evaluation (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    consequence_id BIGINT NOT NULL,
    issue_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    evaluation_type VARCHAR(16) NOT NULL,
    score DECIMAL(5,2) NOT NULL,
    evaluation_comment VARCHAR(1000) NOT NULL,
    evaluated_by BIGINT NOT NULL,
    evaluated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_qs_partner_evaluation (tenant_id, consequence_id, deleted_flag),
    KEY idx_qs_partner_score (tenant_id, partner_id, evaluation_type, evaluated_at),
    CONSTRAINT fk_qs_eval_consequence FOREIGN KEY (consequence_id) REFERENCES qs_consequence(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_eval_issue FOREIGN KEY (issue_id) REFERENCES qs_issue(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_eval_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_qs_eval_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT ck_qs_eval_type CHECK (evaluation_type IN ('QUALITY','SAFETY')),
    CONSTRAINT ck_qs_eval_score CHECK (score >= 0 AND score <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商或分包商质量安全评价事实';

ALTER TABLE qs_consequence
    ADD CONSTRAINT fk_qs_consequence_evaluation FOREIGN KEY (evaluation_id) REFERENCES qs_partner_evaluation(id) ON DELETE RESTRICT;

INSERT IGNORE INTO sys_menu(id,tenant_id,parent_id,menu_name,menu_type,path,component,perms,icon,order_num,status,visible) VALUES
(1098,0,2,'质量安全整改','MENU','quality-safety','quality-safety/index','quality:safety:query','safety-certificate',9,'ENABLE',1),
(1099,0,1098,'维护检查计划','BUTTON',NULL,NULL,'quality:safety:plan:maintain',NULL,1,'ENABLE',1),
(1100,0,1098,'维护检查记录与问题','BUTTON',NULL,NULL,'quality:safety:inspection:maintain',NULL,2,'ENABLE',1),
(1101,0,1098,'提交整改','BUTTON',NULL,NULL,'quality:safety:rectify',NULL,3,'ENABLE',1),
(1102,0,1098,'复验与关闭','BUTTON',NULL,NULL,'quality:safety:reinspect',NULL,4,'ENABLE',1),
(1103,0,1098,'处罚成本与评价','BUTTON',NULL,NULL,'quality:safety:consequence',NULL,5,'ENABLE',1);

INSERT IGNORE INTO sys_role_menu(id,role_id,menu_id)
SELECT 188000000+r.id*10000+m.id,r.id,m.id
FROM sys_role r JOIN sys_menu m ON m.id BETWEEN 1098 AND 1103
WHERE r.role_code IN ('SUPER_ADMIN','ADMIN','PROJECT_MANAGER','COST_MANAGER','AUDITOR') AND r.deleted_flag=0;

SET FOREIGN_KEY_CHECKS = 1;
