ALTER TABLE tech_item
    ADD COLUMN source_type VARCHAR(40) NULL COMMENT '真实技术业务来源类型',
    ADD COLUMN source_id BIGINT NULL COMMENT '真实技术业务来源ID',
    ADD UNIQUE KEY uk_tech_item_source (tenant_id, source_type, source_id);

CREATE TABLE technical_scheme (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    scheme_code VARCHAR(64) NOT NULL,
    scheme_name VARCHAR(200) NOT NULL,
    scheme_type VARCHAR(30) NOT NULL,
    responsible_user_id BIGINT NOT NULL,
    planned_effective_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    approval_instance_id BIGINT NULL,
    approved_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_technical_scheme_code (tenant_id, project_id, scheme_code, deleted_flag),
    KEY idx_technical_scheme_status (tenant_id, project_id, status),
    CONSTRAINT fk_technical_scheme_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_technical_scheme_approval FOREIGN KEY (approval_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT,
    CONSTRAINT ck_technical_scheme_type CHECK (scheme_type IN ('GENERAL','SPECIAL','CONSTRUCTION_ORGANIZATION','METHOD_STATEMENT')),
    CONSTRAINT ck_technical_scheme_status CHECK (status IN ('DRAFT','PENDING','APPROVED','REJECTED','SUPERSEDED','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_drawing (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_code VARCHAR(64) NOT NULL,
    drawing_name VARCHAR(200) NOT NULL,
    specialty VARCHAR(50) NOT NULL,
    source_organization VARCHAR(200) NOT NULL,
    current_version_id BIGINT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_drawing_code (tenant_id, project_id, drawing_code, deleted_flag),
    KEY idx_tech_drawing_project (tenant_id, project_id, specialty, status),
    CONSTRAINT fk_tech_drawing_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_drawing_status CHECK (status IN ('ACTIVE','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_drawing_version (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_id BIGINT NOT NULL,
    version_no VARCHAR(30) NOT NULL,
    previous_version_id BIGINT NULL,
    source_rfi_id BIGINT NULL,
    received_at DATETIME NOT NULL,
    received_by BIGINT NOT NULL,
    change_summary VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    approved_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_drawing_version (tenant_id, drawing_id, version_no, deleted_flag),
    KEY idx_tech_drawing_version_status (tenant_id, project_id, status),
    CONSTRAINT fk_tech_drawing_version_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_drawing_version_drawing FOREIGN KEY (drawing_id) REFERENCES tech_drawing(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_drawing_version_previous FOREIGN KEY (previous_version_id) REFERENCES tech_drawing_version(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_drawing_version_status CHECK (status IN ('RECEIVED','UNDER_REVIEW','RFI_PENDING','APPROVED','SUPERSEDED','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_drawing_review (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_version_id BIGINT NOT NULL,
    review_code VARCHAR(64) NOT NULL,
    review_date DATE NOT NULL,
    chair_user_id BIGINT NOT NULL,
    participant_summary VARCHAR(500) NOT NULL,
    conclusion VARCHAR(20) NOT NULL,
    review_summary VARCHAR(1000) NOT NULL,
    requires_rfi TINYINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_drawing_review_code (tenant_id, project_id, review_code, deleted_flag),
    UNIQUE KEY uk_tech_drawing_review_version (tenant_id, drawing_version_id, deleted_flag),
    CONSTRAINT fk_tech_drawing_review_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_drawing_review_version FOREIGN KEY (drawing_version_id) REFERENCES tech_drawing_version(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_drawing_review_conclusion CHECK (conclusion IN ('PASS','CONDITIONAL','REJECTED')),
    CONSTRAINT ck_tech_drawing_review_status CHECK (status IN ('DRAFT','CONFIRMED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_rfi (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_version_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    rfi_code VARCHAR(64) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    question VARCHAR(2000) NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    raised_by BIGINT NOT NULL,
    raised_at DATETIME NOT NULL,
    response_due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    closed_by BIGINT NULL,
    closed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_rfi_code (tenant_id, project_id, rfi_code, deleted_flag),
    KEY idx_tech_rfi_status (tenant_id, project_id, status, response_due_date),
    CONSTRAINT fk_tech_rfi_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_rfi_drawing_version FOREIGN KEY (drawing_version_id) REFERENCES tech_drawing_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_rfi_review FOREIGN KEY (review_id) REFERENCES tech_drawing_review(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_rfi_priority CHECK (priority IN ('NORMAL','HIGH','URGENT')),
    CONSTRAINT ck_tech_rfi_status CHECK (status IN ('DRAFT','SUBMITTED','RESPONDED','CHANGE_PENDING','CLOSED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_rfi_response (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    rfi_id BIGINT NOT NULL,
    response_no INT NOT NULL,
    response_content VARCHAR(2000) NOT NULL,
    change_required TINYINT NOT NULL DEFAULT 0,
    responder_name VARCHAR(100) NOT NULL,
    responded_by BIGINT NOT NULL,
    responded_at DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    reviewed_by BIGINT NULL,
    reviewed_at DATETIME NULL,
    review_comment VARCHAR(500) NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_rfi_response_no (tenant_id, rfi_id, response_no),
    CONSTRAINT fk_tech_rfi_response_rfi FOREIGN KEY (rfi_id) REFERENCES tech_rfi(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_rfi_response_status CHECK (status IN ('SUBMITTED','ACCEPTED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_disclosure (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_version_id BIGINT NOT NULL,
    scheme_id BIGINT NULL,
    disclosure_code VARCHAR(64) NOT NULL,
    disclosure_title VARCHAR(200) NOT NULL,
    disclosure_date DATE NOT NULL,
    presenter_user_id BIGINT NOT NULL,
    recipient_summary VARCHAR(500) NOT NULL,
    disclosure_content VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_disclosure_code (tenant_id, project_id, disclosure_code, deleted_flag),
    CONSTRAINT fk_tech_disclosure_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_disclosure_version FOREIGN KEY (drawing_version_id) REFERENCES tech_drawing_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_disclosure_scheme FOREIGN KEY (scheme_id) REFERENCES technical_scheme(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_disclosure_status CHECK (status IN ('DRAFT','CONFIRMED','VOID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_construction_reference (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_version_id BIGINT NOT NULL,
    disclosure_id BIGINT NOT NULL,
    daily_log_id BIGINT NOT NULL,
    wbs_task_id BIGINT NOT NULL,
    reference_date DATE NOT NULL,
    work_area VARCHAR(200) NOT NULL,
    reference_description VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RECORDED',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_construction_reference (tenant_id, drawing_version_id, daily_log_id, wbs_task_id, deleted_flag),
    KEY idx_tech_construction_reference_project (tenant_id, project_id, reference_date),
    CONSTRAINT fk_tech_reference_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_reference_version FOREIGN KEY (drawing_version_id) REFERENCES tech_drawing_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_reference_disclosure FOREIGN KEY (disclosure_id) REFERENCES tech_disclosure(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_reference_daily_log FOREIGN KEY (daily_log_id) REFERENCES site_daily_log(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_reference_wbs FOREIGN KEY (wbs_task_id) REFERENCES project_wbs_task(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_reference_status CHECK (status IN ('RECORDED','VOID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tech_acceptance_archive (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    drawing_version_id BIGINT NOT NULL,
    construction_reference_id BIGINT NOT NULL,
    quality_inspection_id BIGINT NOT NULL,
    archive_code VARCHAR(64) NOT NULL,
    acceptance_date DATE NOT NULL,
    acceptance_conclusion VARCHAR(20) NOT NULL,
    archive_location VARCHAR(300) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    archived_by BIGINT NULL,
    archived_at DATETIME NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tech_archive_code (tenant_id, project_id, archive_code, deleted_flag),
    UNIQUE KEY uk_tech_archive_reference (tenant_id, construction_reference_id, deleted_flag),
    CONSTRAINT fk_tech_archive_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_archive_version FOREIGN KEY (drawing_version_id) REFERENCES tech_drawing_version(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_archive_reference FOREIGN KEY (construction_reference_id) REFERENCES tech_construction_reference(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tech_archive_inspection FOREIGN KEY (quality_inspection_id) REFERENCES qs_inspection_record(id) ON DELETE RESTRICT,
    CONSTRAINT ck_tech_archive_conclusion CHECK (acceptance_conclusion IN ('PASS','CONDITIONAL_PASS')),
    CONSTRAINT ck_tech_archive_status CHECK (status IN ('DRAFT','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE tech_drawing_version
    ADD CONSTRAINT fk_tech_drawing_version_source_rfi FOREIGN KEY (source_rfi_id) REFERENCES tech_rfi(id) ON DELETE RESTRICT;

INSERT IGNORE INTO wf_template(id,tenant_id,template_code,template_name,business_type,enabled,created_by,remark)
VALUES(50037,0,'TPL-TECHNICAL-SCHEME-001','技术方案审批','TECHNICAL_SCHEME',1,1,'技术方案：项目经理与总工程师两级审批');

INSERT IGNORE INTO wf_template_node(id,tenant_id,template_id,node_code,node_name,node_order,node_type,approve_mode,approver_config,allow_transfer,allow_add_sign,timeout_hours) VALUES
(53701,0,50037,'N1','项目经理审批',1,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53702,0,50037,'N2','总工程师审批',2,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,72);

INSERT IGNORE INTO sys_menu(id,tenant_id,parent_id,menu_name,menu_type,path,component,perms,icon,order_num,status,visible) VALUES
(1111,0,2,'技术管理','MENU','technical-management','technical-management/index','technical:query','file-search',9,'ENABLE',1),
(1112,0,1111,'维护技术方案','BUTTON',NULL,NULL,'technical:scheme:maintain',NULL,1,'ENABLE',1),
(1113,0,1111,'提交技术方案','BUTTON',NULL,NULL,'technical:scheme:submit',NULL,2,'ENABLE',1),
(1114,0,1111,'接收图纸版本','BUTTON',NULL,NULL,'technical:drawing:receive',NULL,3,'ENABLE',1),
(1115,0,1111,'确认图纸会审','BUTTON',NULL,NULL,'technical:drawing:review',NULL,4,'ENABLE',1),
(1116,0,1111,'发起RFI','BUTTON',NULL,NULL,'technical:rfi:raise',NULL,5,'ENABLE',1),
(1117,0,1111,'回复RFI','BUTTON',NULL,NULL,'technical:rfi:respond',NULL,6,'ENABLE',1),
(1118,0,1111,'确认RFI回复','BUTTON',NULL,NULL,'technical:rfi:accept',NULL,7,'ENABLE',1),
(1119,0,1111,'技术交底与施工引用','BUTTON',NULL,NULL,'technical:disclosure:maintain',NULL,8,'ENABLE',1),
(1120,0,1111,'验收归档','BUTTON',NULL,NULL,'technical:archive:confirm',NULL,9,'ENABLE',1);

INSERT IGNORE INTO sys_role_menu(id,role_id,menu_id)
SELECT 190000000+r.id*10000+m.id,r.id,m.id FROM sys_role r JOIN sys_menu m ON m.id BETWEEN 1111 AND 1120
WHERE r.role_code IN ('SUPER_ADMIN','ADMIN','PROJECT_MANAGER','CHIEF_ENGINEER') AND r.deleted_flag=0;
