ALTER TABLE owner_settlement
    ADD COLUMN settlement_type VARCHAR(32) NOT NULL DEFAULT 'PROGRESS' COMMENT 'PROGRESS/FINAL';

CREATE TABLE project_closeout (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    closeout_code VARCHAR(64) NOT NULL,
    planned_completion_date DATE NOT NULL,
    actual_completion_date DATE NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'INITIATED',
    final_owner_settlement_id BIGINT NULL,
    tail_collection_verified_at DATETIME NULL,
    closed_by BIGINT NULL,
    closed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_closeout_project (tenant_id,project_id,deleted_flag),
    UNIQUE KEY uk_project_closeout_code (tenant_id,closeout_code,deleted_flag),
    UNIQUE KEY uk_project_closeout_settlement (tenant_id,final_owner_settlement_id),
    CONSTRAINT fk_project_closeout_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_closeout_settlement FOREIGN KEY (final_owner_settlement_id) REFERENCES owner_settlement(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE closeout_section_acceptance (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    closeout_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    wbs_task_id BIGINT NOT NULL,
    quality_inspection_id BIGINT NOT NULL,
    acceptance_code VARCHAR(64) NOT NULL,
    acceptance_name VARCHAR(200) NOT NULL,
    acceptance_date DATE NOT NULL,
    conclusion VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_closeout_section_code (tenant_id,acceptance_code,deleted_flag),
    UNIQUE KEY uk_closeout_section_wbs (tenant_id,closeout_id,wbs_task_id,deleted_flag),
    CONSTRAINT fk_closeout_section_closeout FOREIGN KEY (closeout_id) REFERENCES project_closeout(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_section_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_section_wbs FOREIGN KEY (wbs_task_id) REFERENCES project_wbs_task(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_section_quality FOREIGN KEY (quality_inspection_id) REFERENCES qs_inspection_record(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE closeout_final_acceptance (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    closeout_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    acceptance_code VARCHAR(64) NOT NULL,
    acceptance_date DATE NOT NULL,
    organizer VARCHAR(200) NOT NULL,
    participant_summary VARCHAR(1000) NOT NULL,
    conclusion VARCHAR(32) NOT NULL,
    acceptance_summary VARCHAR(2000) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    approval_instance_id BIGINT NULL,
    approved_by BIGINT NULL,
    approved_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_closeout_final_closeout (tenant_id,closeout_id,deleted_flag),
    UNIQUE KEY uk_closeout_final_code (tenant_id,acceptance_code,deleted_flag),
    CONSTRAINT fk_closeout_final_closeout FOREIGN KEY (closeout_id) REFERENCES project_closeout(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_final_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_final_approval FOREIGN KEY (approval_instance_id) REFERENCES wf_instance(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE closeout_warranty (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    closeout_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    receivable_id BIGINT NOT NULL,
    warranty_code VARCHAR(64) NOT NULL,
    warranty_amount DECIMAL(18,2) NOT NULL,
    warranty_start_date DATE NOT NULL,
    warranty_end_date DATE NOT NULL,
    responsible_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    released_by BIGINT NULL,
    released_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_closeout_warranty_code (tenant_id,warranty_code,deleted_flag),
    UNIQUE KEY uk_closeout_warranty_receivable (tenant_id,receivable_id,deleted_flag),
    CONSTRAINT fk_closeout_warranty_closeout FOREIGN KEY (closeout_id) REFERENCES project_closeout(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_warranty_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_warranty_contract FOREIGN KEY (contract_id) REFERENCES ct_contract(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_warranty_receivable FOREIGN KEY (receivable_id) REFERENCES account_receivable(id) ON DELETE RESTRICT,
    CONSTRAINT ck_closeout_warranty_amount CHECK (warranty_amount>0),
    CONSTRAINT ck_closeout_warranty_dates CHECK (warranty_end_date>=warranty_start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE closeout_defect (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    closeout_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    warranty_id BIGINT NOT NULL,
    defect_code VARCHAR(64) NOT NULL,
    defect_title VARCHAR(200) NOT NULL,
    defect_description VARCHAR(2000) NOT NULL,
    responsible_user_id BIGINT NOT NULL,
    rectification_deadline DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    rectification_content VARCHAR(2000) NULL,
    rectified_by BIGINT NULL,
    rectified_at DATETIME NULL,
    verified_by BIGINT NULL,
    verified_at DATETIME NULL,
    verification_comment VARCHAR(1000) NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_closeout_defect_code (tenant_id,defect_code,deleted_flag),
    KEY idx_closeout_defect_status (tenant_id,closeout_id,status),
    CONSTRAINT fk_closeout_defect_closeout FOREIGN KEY (closeout_id) REFERENCES project_closeout(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_defect_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_defect_warranty FOREIGN KEY (warranty_id) REFERENCES closeout_warranty(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE closeout_archive_transfer (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    closeout_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    transfer_code VARCHAR(64) NOT NULL,
    transfer_date DATE NOT NULL,
    recipient_organization VARCHAR(200) NOT NULL,
    recipient_name VARCHAR(100) NOT NULL,
    archive_location VARCHAR(300) NOT NULL,
    transfer_scope VARCHAR(2000) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    accepted_by BIGINT NULL,
    accepted_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_closeout_archive_code (tenant_id,transfer_code,deleted_flag),
    UNIQUE KEY uk_closeout_archive_closeout (tenant_id,closeout_id,deleted_flag),
    CONSTRAINT fk_closeout_archive_closeout FOREIGN KEY (closeout_id) REFERENCES project_closeout(id) ON DELETE RESTRICT,
    CONSTRAINT fk_closeout_archive_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO wf_template(id,tenant_id,template_code,template_name,business_type,enabled,amount_min,amount_max,created_by,remark)
VALUES(50038,0,'TPL-PROJECT-FINAL-ACCEPTANCE-001','项目竣工验收审批流程','PROJECT_FINAL_ACCEPTANCE',1,0,999999999999.99,1,'竣工收尾闭环：项目、工程、公司三级确认');
INSERT IGNORE INTO wf_template_node(id,tenant_id,template_id,node_code,node_name,node_order,node_type,approve_mode,approver_config,allow_transfer,allow_add_sign,timeout_hours)
VALUES
(53801,0,50038,'N1','项目经理确认',1,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53802,0,50038,'N2','工程管理确认',2,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,48),
(53803,0,50038,'N3','公司竣工确认',3,'APPROVAL','SEQUENTIAL',JSON_OBJECT('type','USER','userId',1),1,1,72);

INSERT IGNORE INTO sys_menu(id,tenant_id,parent_id,menu_name,menu_type,path,component,perms,icon,order_num,status,visible)
VALUES
(1121,0,2,'项目竣工收尾','MENU','project-closeout','project-closeout/index','closeout:query','check-circle',13,'ENABLE',1),
(1122,0,1121,'发起项目收尾','BUTTON',NULL,NULL,'closeout:initiate',NULL,1,'ENABLE',1),
(1123,0,1121,'维护分项验收','BUTTON',NULL,NULL,'closeout:section:maintain',NULL,2,'ENABLE',1),
(1124,0,1121,'提交竣工验收','BUTTON',NULL,NULL,'closeout:acceptance:submit',NULL,3,'ENABLE',1),
(1125,0,1121,'绑定竣工结算','BUTTON',NULL,NULL,'closeout:settlement:bind',NULL,4,'ENABLE',1),
(1126,0,1121,'确认尾款回收','BUTTON',NULL,NULL,'closeout:collection:verify',NULL,5,'ENABLE',1),
(1127,0,1121,'维护质保责任','BUTTON',NULL,NULL,'closeout:warranty:maintain',NULL,6,'ENABLE',1),
(1128,0,1121,'整改缺陷','BUTTON',NULL,NULL,'closeout:defect:maintain',NULL,7,'ENABLE',1),
(1129,0,1121,'复验缺陷','BUTTON',NULL,NULL,'closeout:defect:verify',NULL,8,'ENABLE',1),
(1130,0,1121,'移交竣工档案','BUTTON',NULL,NULL,'closeout:archive:maintain',NULL,9,'ENABLE',1),
(1131,0,1121,'关闭项目','BUTTON',NULL,NULL,'closeout:close',NULL,10,'ENABLE',1);
INSERT IGNORE INTO sys_role_menu(id,role_id,menu_id)
SELECT 191000000+r.id*10000+m.id,r.id,m.id FROM sys_role r JOIN sys_menu m ON m.id BETWEEN 1121 AND 1131
WHERE r.role_code IN ('SUPER_ADMIN','ADMIN','PROJECT_MANAGER','FINANCE','COST_MANAGER','AUDITOR') AND r.deleted_flag=0;
