CREATE TABLE mat_stock_transfer (
    id BIGINT NOT NULL COMMENT '调拨事实ID，雪花ID',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    project_id BIGINT NOT NULL COMMENT '两端仓库所属项目ID',
    source_stock_id BIGINT NOT NULL COMMENT '来源库存ID',
    target_stock_id BIGINT NOT NULL COMMENT '目标库存ID',
    source_warehouse_id BIGINT NOT NULL COMMENT '来源仓库ID',
    target_warehouse_id BIGINT NOT NULL COMMENT '目标仓库ID',
    material_id BIGINT NOT NULL COMMENT '物料ID',
    quantity DECIMAL(18,4) NOT NULL COMMENT '调拨数量',
    unit_cost DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '来源移动加权平均单位成本',
    amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '调拨库存价值',
    idempotency_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户内幂等键',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING处理中；COMPLETED已完成',
    completed_at DATETIME NULL COMMENT '原子过账完成时间',
    created_by BIGINT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT NULL COMMENT '更新人',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否，1是',
    remark VARCHAR(500) NULL COMMENT '调拨原因',
    PRIMARY KEY (id),
    UNIQUE KEY uk_stock_transfer_tenant_key (tenant_id, idempotency_key),
    KEY idx_stock_transfer_project_created (tenant_id, project_id, created_at),
    KEY idx_stock_transfer_source_stock (tenant_id, source_stock_id),
    KEY idx_stock_transfer_target_stock (tenant_id, target_stock_id),
    CONSTRAINT fk_stock_transfer_source_stock FOREIGN KEY (source_stock_id) REFERENCES mat_stock (id) ON DELETE RESTRICT,
    CONSTRAINT fk_stock_transfer_target_stock FOREIGN KEY (target_stock_id) REFERENCES mat_stock (id) ON DELETE RESTRICT,
    CONSTRAINT ck_stock_transfer_route CHECK (source_stock_id <> target_stock_id AND source_warehouse_id <> target_warehouse_id),
    CONSTRAINT ck_stock_transfer_values CHECK (quantity > 0 AND unit_cost >= 0 AND amount >= 0),
    CONSTRAINT ck_stock_transfer_status CHECK (status IN ('PENDING', 'COMPLETED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='同项目跨仓库存调拨事实表';
