-- V1__init_schema.sql
-- 建筑工程总包项目全过程管理系统核心表初始化脚本
-- 数据库：MySQL 8.0+
-- ID 策略：后端雪花 ID / ASSIGN_ID，数据库不使用 AUTO_INCREMENT

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS pm_project (
    id BIGINT NOT NULL COMMENT '项目ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    org_id BIGINT NULL COMMENT '所属组织/项目部ID',
    project_code VARCHAR(64) NOT NULL COMMENT '项目编号',
    project_name VARCHAR(200) NOT NULL COMMENT '项目名称',
    project_type VARCHAR(50) NULL COMMENT '项目类型',
    project_address VARCHAR(300) NULL COMMENT '项目地址',
    owner_unit VARCHAR(200) NULL COMMENT '建设单位',
    supervisor_unit VARCHAR(200) NULL COMMENT '监理单位',
    design_unit VARCHAR(200) NULL COMMENT '设计单位',
    contract_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总包合同金额',
    target_cost DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '目标成本',
    planned_start_date DATE NULL COMMENT '计划开工日期',
    planned_end_date DATE NULL COMMENT '计划竣工日期',
    actual_start_date DATE NULL COMMENT '实际开工日期',
    actual_end_date DATE NULL COMMENT '实际竣工日期',
    project_manager_id BIGINT NULL COMMENT '项目经理用户ID',
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT' COMMENT '项目状态',
    approval_status VARCHAR(50) NULL COMMENT '审批状态',
    created_by BIGINT NULL COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT NULL COMMENT '更新人',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否，1是',
    remark VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (id),
    UNIQUE KEY uk_pm_project_code (tenant_id, project_code),
    KEY idx_pm_project_name (project_name),
    KEY idx_pm_project_status (status),
    KEY idx_pm_project_manager (project_manager_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='项目表';

CREATE TABLE IF NOT EXISTS md_partner (
    id BIGINT NOT NULL COMMENT '合作方ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    partner_code VARCHAR(64) NOT NULL COMMENT '合作方编号',
    partner_name VARCHAR(200) NOT NULL COMMENT '合作方名称',
    partner_type VARCHAR(50) NOT NULL COMMENT '供应商/分包商/租赁商/服务商等',
    credit_code VARCHAR(100) NULL COMMENT '统一社会信用代码',
    legal_person VARCHAR(100) NULL COMMENT '法人',
    contact_name VARCHAR(100) NULL COMMENT '联系人',
    contact_phone VARCHAR(50) NULL COMMENT '联系电话',
    bank_name VARCHAR(200) NULL COMMENT '开户行',
    bank_account VARCHAR(100) NULL COMMENT '银行账号',
    qualification_level VARCHAR(100) NULL COMMENT '资质等级',
    blacklist_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否黑名单',
    risk_level VARCHAR(50) NULL COMMENT '风险等级',
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLE' COMMENT '状态',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_md_partner_code (tenant_id, partner_code),
    KEY idx_md_partner_name (partner_name),
    KEY idx_md_partner_type (partner_type),
    KEY idx_md_partner_blacklist (blacklist_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合作方表';

CREATE TABLE IF NOT EXISTS ct_contract (
    id BIGINT NOT NULL COMMENT '合同ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    org_id BIGINT NULL COMMENT '所属组织ID',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    partner_id BIGINT NULL COMMENT '合作方ID',
    contract_code VARCHAR(64) NOT NULL COMMENT '合同编号',
    contract_name VARCHAR(200) NOT NULL COMMENT '合同名称',
    contract_type VARCHAR(50) NOT NULL COMMENT '总包/分包/采购/租赁/服务等',
    party_a VARCHAR(200) NULL COMMENT '甲方',
    party_b VARCHAR(200) NULL COMMENT '乙方',
    contract_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '原合同金额',
    current_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '当前合同金额=原合同金额+已生效变更',
    tax_rate DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT '税率',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税额',
    amount_without_tax DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '不含税金额',
    signed_date DATE NULL COMMENT '签订日期',
    start_date DATE NULL COMMENT '合同开始日期',
    end_date DATE NULL COMMENT '合同结束日期',
    payment_method VARCHAR(100) NULL COMMENT '付款方式',
    settlement_method VARCHAR(100) NULL COMMENT '结算方式',
    warranty_rate DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT '质保金比例',
    warranty_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '质保金金额',
    contract_status VARCHAR(50) NOT NULL DEFAULT 'DRAFT' COMMENT '合同业务状态',
    approval_status VARCHAR(50) NOT NULL DEFAULT 'DRAFT' COMMENT '审批状态',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ct_contract_code (tenant_id, contract_code),
    KEY idx_ct_contract_project (project_id),
    KEY idx_ct_contract_partner (partner_id),
    KEY idx_ct_contract_type (contract_type),
    KEY idx_ct_contract_status (contract_status, approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合同主表';

CREATE TABLE IF NOT EXISTS cost_item (
    id BIGINT NOT NULL COMMENT '成本ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    org_id BIGINT NULL COMMENT '所属组织ID',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    contract_id BIGINT NULL COMMENT '合同ID',
    partner_id BIGINT NULL COMMENT '合作方ID',
    cost_subject_id BIGINT NULL COMMENT '成本科目ID',
    cost_type VARCHAR(50) NOT NULL COMMENT '材料/分包/机械/人工/签证/管理费等',
    amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '成本金额',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税额',
    amount_without_tax DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '不含税金额',
    source_type VARCHAR(50) NOT NULL COMMENT '来源类型，如 MAT_RECEIPT/SUB_MEASURE/VAR_ORDER',
    source_id BIGINT NOT NULL COMMENT '来源单据主表ID',
    source_item_id BIGINT NOT NULL DEFAULT 0 COMMENT '来源单据明细ID，不按明细拆分时为0',
    cost_date DATE NOT NULL COMMENT '成本发生日期',
    cost_status VARCHAR(50) NOT NULL DEFAULT 'CONFIRMED' COMMENT '暂估/已确认/已结算/已冲销',
    generated_flag TINYINT NOT NULL DEFAULT 1 COMMENT '是否系统生成',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cost_source_item (source_type, source_id, source_item_id, cost_type),
    KEY idx_cost_project (project_id),
    KEY idx_cost_contract (contract_id),
    KEY idx_cost_source (source_type, source_id),
    KEY idx_cost_subject (cost_subject_id),
    KEY idx_cost_date (cost_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='成本明细表';

CREATE TABLE IF NOT EXISTS wf_template (
    id BIGINT NOT NULL COMMENT '审批模板ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    template_code VARCHAR(64) NOT NULL COMMENT '模板编码',
    template_name VARCHAR(200) NOT NULL COMMENT '模板名称',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    amount_min DECIMAL(18,2) NULL COMMENT '适用金额下限',
    amount_max DECIMAL(18,2) NULL COMMENT '适用金额上限',
    condition_rule JSON NULL COMMENT '流程匹配条件',
    form_schema JSON NULL COMMENT '动态表单Schema',
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wf_template_code (tenant_id, template_code),
    KEY idx_wf_template_business (business_type, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批模板表';

CREATE TABLE IF NOT EXISTS wf_template_node (
    id BIGINT NOT NULL COMMENT '模板节点ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    template_id BIGINT NOT NULL COMMENT '模板ID',
    node_code VARCHAR(64) NOT NULL COMMENT '节点编码',
    node_name VARCHAR(200) NOT NULL COMMENT '节点名称',
    node_order INT NOT NULL COMMENT '节点顺序',
    node_type VARCHAR(50) NOT NULL DEFAULT 'APPROVAL' COMMENT '节点类型',
    approve_mode VARCHAR(50) NOT NULL DEFAULT 'SEQUENTIAL' COMMENT '审批模式',
    approver_config JSON NOT NULL COMMENT '审批人配置',
    pass_rule_json JSON NULL COMMENT '节点通过规则',
    reject_rule_json JSON NULL COMMENT '节点驳回规则',
    condition_rule JSON NULL COMMENT '节点执行条件',
    node_config JSON NULL COMMENT '节点扩展配置',
    allow_transfer TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许转办',
    allow_add_sign TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许加签',
    timeout_hours INT NULL COMMENT '超时时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wf_template_node_code (template_id, node_code),
    KEY idx_wf_template_node_template (template_id, node_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批模板节点表';

CREATE TABLE IF NOT EXISTS wf_instance (
    id BIGINT NOT NULL COMMENT '审批实例ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    template_id BIGINT NOT NULL COMMENT '审批模板ID',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT NOT NULL COMMENT '业务单据ID',
    project_id BIGINT NULL COMMENT '项目ID',
    contract_id BIGINT NULL COMMENT '合同ID',
    title VARCHAR(300) NOT NULL COMMENT '审批标题',
    amount DECIMAL(18,2) NULL COMMENT '审批金额',
    instance_status VARCHAR(50) NOT NULL DEFAULT 'RUNNING' COMMENT '实例状态',
    current_round INT NOT NULL DEFAULT 1 COMMENT '当前审批轮次',
    resubmit_count INT NOT NULL DEFAULT 0 COMMENT '重新提交次数',
    business_revision INT NOT NULL DEFAULT 1 COMMENT '业务版本',
    initiator_id BIGINT NOT NULL COMMENT '发起人ID',
    business_summary JSON NULL COMMENT '业务摘要',
    variables JSON NULL COMMENT '流程变量',
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发起时间',
    ended_at DATETIME NULL COMMENT '结束时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wf_instance_business (business_type, business_id),
    KEY idx_wf_instance_initiator (initiator_id, instance_status),
    KEY idx_wf_instance_project (project_id),
    KEY idx_wf_instance_status (instance_status, current_round)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批实例表';

CREATE TABLE IF NOT EXISTS wf_node_instance (
    id BIGINT NOT NULL COMMENT '节点实例ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    instance_id BIGINT NOT NULL COMMENT '审批实例ID',
    template_node_id BIGINT NULL COMMENT '模板节点ID',
    node_code VARCHAR(64) NOT NULL COMMENT '节点编码',
    node_name VARCHAR(200) NOT NULL COMMENT '节点名称',
    node_order INT NOT NULL COMMENT '节点顺序',
    approve_mode VARCHAR(50) NOT NULL COMMENT '审批模式',
    node_status VARCHAR(50) NOT NULL DEFAULT 'WAITING' COMMENT '节点状态',
    round_no INT NOT NULL DEFAULT 1 COMMENT '审批轮次',
    pass_rule_json JSON NULL COMMENT '节点通过规则',
    reject_rule_json JSON NULL COMMENT '节点驳回规则',
    started_at DATETIME NULL COMMENT '开始时间',
    ended_at DATETIME NULL COMMENT '结束时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_wf_node_instance_instance (instance_id, round_no, node_order),
    KEY idx_wf_node_instance_status (node_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批节点实例表';

CREATE TABLE IF NOT EXISTS wf_task (
    id BIGINT NOT NULL COMMENT '审批任务ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    instance_id BIGINT NOT NULL COMMENT '审批实例ID',
    node_instance_id BIGINT NOT NULL COMMENT '节点实例ID',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT NOT NULL COMMENT '业务单据ID',
    approver_id BIGINT NOT NULL COMMENT '审批人ID',
    approver_name VARCHAR(100) NULL COMMENT '审批人姓名',
    task_status VARCHAR(50) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
    round_no INT NOT NULL DEFAULT 1 COMMENT '审批轮次',
    task_version INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '接收时间',
    handled_at DATETIME NULL COMMENT '处理时间',
    action_type VARCHAR(50) NULL COMMENT '处理动作',
    comment VARCHAR(1000) NULL COMMENT '审批意见',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_wf_task_todo (approver_id, task_status, received_at),
    KEY idx_wf_task_instance (instance_id, round_no),
    KEY idx_wf_task_node (node_instance_id),
    KEY idx_wf_task_business (business_type, business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批任务表';

CREATE TABLE IF NOT EXISTS wf_record (
    id BIGINT NOT NULL COMMENT '审批记录ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    instance_id BIGINT NOT NULL COMMENT '审批实例ID',
    node_instance_id BIGINT NULL COMMENT '节点实例ID，提交/撤回等可为空',
    task_id BIGINT NULL COMMENT '审批任务ID',
    round_no INT NOT NULL DEFAULT 1 COMMENT '审批轮次',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    business_id BIGINT NOT NULL COMMENT '业务单据ID',
    node_code VARCHAR(64) NULL COMMENT '节点编码',
    node_name VARCHAR(200) NULL COMMENT '节点名称',
    action_type VARCHAR(50) NOT NULL COMMENT '动作类型',
    action_name VARCHAR(100) NOT NULL COMMENT '动作名称',
    operator_id BIGINT NOT NULL COMMENT '操作人ID',
    operator_name VARCHAR(100) NULL COMMENT '操作人姓名',
    comment VARCHAR(1000) NULL COMMENT '审批意见',
    record_status VARCHAR(50) NOT NULL DEFAULT 'EFFECTIVE' COMMENT '记录状态',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_wf_record_instance (instance_id, round_no, created_at),
    KEY idx_wf_record_task (task_id),
    KEY idx_wf_record_node (node_instance_id),
    KEY idx_wf_record_business (business_type, business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批记录表';

CREATE TABLE IF NOT EXISTS wf_idempotency (
    id BIGINT NOT NULL COMMENT '幂等记录ID，雪花ID',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    business_type VARCHAR(50) NULL COMMENT '业务类型',
    business_id BIGINT NULL COMMENT '业务ID',
    request_hash VARCHAR(128) NULL COMMENT '请求摘要',
    response_json JSON NULL COMMENT '首次响应结果',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expired_at DATETIME NULL COMMENT '过期时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_wf_idempotency (tenant_id, user_id, idempotency_key),
    KEY idx_wf_idempotency_expired (expired_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审批幂等表';

SET FOREIGN_KEY_CHECKS = 1;
