CREATE TABLE mat_material_return (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    requisition_id BIGINT NOT NULL,
    return_code VARCHAR(50) NOT NULL,
    return_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    confirmed_by BIGINT NOT NULL,
    confirmed_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_material_return_code (tenant_id, return_code),
    UNIQUE KEY uk_material_return_idempotency (tenant_id, idempotency_key),
    KEY idx_material_return_requisition (tenant_id, requisition_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='材料退料确认单';

CREATE TABLE mat_material_return_item (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    return_id BIGINT NOT NULL,
    requisition_item_id BIGINT NOT NULL,
    original_stock_txn_id BIGINT NOT NULL,
    original_cost_item_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantity DECIMAL(18,4) NOT NULL,
    unit_cost DECIMAL(18,6) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark TEXT NULL,
    PRIMARY KEY (id),
    KEY idx_material_return_item_header (tenant_id, return_id),
    KEY idx_material_return_item_requisition (tenant_id, requisition_item_id),
    KEY idx_material_return_item_txn (tenant_id, original_stock_txn_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='材料退料明细';
