CREATE TABLE mat_supplier_return (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    warehouse_id BIGINT NULL,
    receipt_id BIGINT NOT NULL,
    return_code VARCHAR(50) NOT NULL,
    return_date DATE NOT NULL,
    return_kind VARCHAR(30) NOT NULL COMMENT 'UNQUALIFIED/ACCEPTED',
    status VARCHAR(30) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_return_code (tenant_id, return_code),
    UNIQUE KEY uk_supplier_return_idempotency (tenant_id, idempotency_key),
    KEY idx_supplier_return_receipt (tenant_id, receipt_id, deleted_flag),
    CONSTRAINT fk_supplier_return_receipt FOREIGN KEY (receipt_id) REFERENCES mat_receipt (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商退货确认单';

CREATE TABLE mat_supplier_return_item (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    return_id BIGINT NOT NULL,
    receipt_item_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    original_stock_txn_id BIGINT NULL,
    original_cost_item_id BIGINT NULL,
    material_id BIGINT NOT NULL,
    quantity DECIMAL(18,4) NOT NULL,
    unit_cost DECIMAL(18,6) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark TEXT NULL,
    PRIMARY KEY (id),
    KEY idx_supplier_return_item_header (tenant_id, return_id),
    KEY idx_supplier_return_item_receipt (tenant_id, receipt_item_id),
    CONSTRAINT fk_supplier_return_item_header FOREIGN KEY (return_id) REFERENCES mat_supplier_return (id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_return_item_receipt FOREIGN KEY (receipt_item_id) REFERENCES mat_receipt_item (id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_return_item_order FOREIGN KEY (order_item_id) REFERENCES mat_purchase_order_item (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商退货明细';
