SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE sp_sourcing_event (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    purchase_request_id BIGINT NOT NULL,
    sourcing_code VARCHAR(64) NOT NULL,
    sourcing_title VARCHAR(200) NOT NULL,
    sourcing_type VARCHAR(16) NOT NULL COMMENT 'INQUIRY/TENDER',
    deadline DATETIME NOT NULL,
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    awarded_quote_id BIGINT NULL,
    awarded_partner_id BIGINT NULL,
    contract_id BIGINT NULL,
    award_reason VARCHAR(1000) NULL,
    published_by BIGINT NULL,
    published_at DATETIME NULL,
    awarded_by BIGINT NULL,
    awarded_at DATETIME NULL,
    contracted_by BIGINT NULL,
    contracted_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_sourcing_code (tenant_id, sourcing_code, deleted_flag),
    UNIQUE KEY uk_sp_sourcing_request (tenant_id, purchase_request_id, deleted_flag),
    KEY idx_sp_sourcing_project_status (tenant_id, project_id, status, deadline),
    CONSTRAINT fk_sp_sourcing_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_sourcing_request FOREIGN KEY (purchase_request_id) REFERENCES mat_purchase_request(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_sourcing_partner FOREIGN KEY (awarded_partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_sourcing_contract FOREIGN KEY (contract_id) REFERENCES ct_contract(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_sourcing_type CHECK (sourcing_type IN ('INQUIRY','TENDER')),
    CONSTRAINT ck_sp_sourcing_status CHECK (status IN ('DRAFT','PUBLISHED','EVALUATING','AWARDED','CONTRACTED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商询价招标事件';

CREATE TABLE sp_sourcing_supplier (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    sourcing_event_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    invitation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    invited_at DATETIME NULL,
    responded_at DATETIME NULL,
    disqualification_reason VARCHAR(500) NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_sourcing_supplier (tenant_id, sourcing_event_id, partner_id, deleted_flag),
    KEY idx_sp_supplier_partner (tenant_id, partner_id, invitation_status),
    CONSTRAINT fk_sp_supplier_event FOREIGN KEY (sourcing_event_id) REFERENCES sp_sourcing_event(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_supplier_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_supplier_status CHECK (invitation_status IN ('PENDING','INVITED','DECLINED','QUOTED','DISQUALIFIED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='招采受邀供应商';

CREATE TABLE sp_supplier_quote (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    sourcing_event_id BIGINT NOT NULL,
    sourcing_supplier_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    quote_code VARCHAR(64) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    delivery_days INT NOT NULL,
    validity_date DATE NOT NULL,
    commercial_terms VARCHAR(2000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    submitted_by BIGINT NULL,
    submitted_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_quote_supplier (tenant_id, sourcing_event_id, partner_id, deleted_flag),
    UNIQUE KEY uk_sp_quote_code (tenant_id, quote_code, deleted_flag),
    KEY idx_sp_quote_event_status (tenant_id, sourcing_event_id, status, total_amount),
    CONSTRAINT fk_sp_quote_event FOREIGN KEY (sourcing_event_id) REFERENCES sp_sourcing_event(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_quote_invitation FOREIGN KEY (sourcing_supplier_id) REFERENCES sp_sourcing_supplier(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_quote_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_quote_amount CHECK (total_amount > 0),
    CONSTRAINT ck_sp_quote_delivery CHECK (delivery_days >= 0),
    CONSTRAINT ck_sp_quote_status CHECK (status IN ('DRAFT','SUBMITTED','WINNER','LOST','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商报价';

CREATE TABLE sp_bid_evaluation (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    sourcing_event_id BIGINT NOT NULL,
    quote_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    commercial_score DECIMAL(5,2) NOT NULL,
    technical_score DECIMAL(5,2) NOT NULL,
    delivery_score DECIMAL(5,2) NOT NULL,
    quality_score DECIMAL(5,2) NOT NULL,
    total_score DECIMAL(5,2) NOT NULL,
    evaluation_comment VARCHAR(1000) NOT NULL,
    evaluated_by BIGINT NOT NULL,
    evaluated_at DATETIME NOT NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_bid_evaluation (tenant_id, quote_id, deleted_flag),
    KEY idx_sp_bid_event_score (tenant_id, sourcing_event_id, total_score),
    CONSTRAINT fk_sp_bid_event FOREIGN KEY (sourcing_event_id) REFERENCES sp_sourcing_event(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_bid_quote FOREIGN KEY (quote_id) REFERENCES sp_supplier_quote(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_bid_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_bid_scores CHECK (commercial_score BETWEEN 0 AND 100 AND technical_score BETWEEN 0 AND 100 AND delivery_score BETWEEN 0 AND 100 AND quality_score BETWEEN 0 AND 100 AND total_score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商比价评审';

ALTER TABLE sp_sourcing_event
    ADD CONSTRAINT fk_sp_sourcing_award_quote FOREIGN KEY (awarded_quote_id) REFERENCES sp_supplier_quote(id) ON DELETE RESTRICT;

CREATE TABLE sp_supplier_return (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    purchase_order_id BIGINT NOT NULL,
    receipt_id BIGINT NOT NULL,
    return_code VARCHAR(64) NOT NULL,
    return_date DATE NOT NULL,
    return_quantity DECIMAL(18,4) NOT NULL,
    return_amount DECIMAL(18,2) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_supplier_return_code (tenant_id, return_code, deleted_flag),
    KEY idx_sp_supplier_return_order (tenant_id, purchase_order_id, status, return_date),
    CONSTRAINT fk_sp_return_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_return_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_return_contract FOREIGN KEY (contract_id) REFERENCES ct_contract(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_return_order FOREIGN KEY (purchase_order_id) REFERENCES mat_purchase_order(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_return_receipt FOREIGN KEY (receipt_id) REFERENCES mat_receipt(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_return_quantity CHECK (return_quantity > 0),
    CONSTRAINT ck_sp_return_amount CHECK (return_amount >= 0),
    CONSTRAINT ck_sp_return_status CHECK (status IN ('DRAFT','CONFIRMED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商退货事实';

CREATE TABLE sp_performance_evaluation (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    purchase_order_id BIGINT NOT NULL,
    evaluation_code VARCHAR(64) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    delivery_score DECIMAL(5,2) NOT NULL,
    quality_score DECIMAL(5,2) NOT NULL,
    service_score DECIMAL(5,2) NOT NULL,
    commercial_score DECIMAL(5,2) NOT NULL,
    total_score DECIMAL(5,2) NOT NULL,
    grade VARCHAR(8) NOT NULL,
    on_time_flag TINYINT NOT NULL,
    approved_receipt_count INT NOT NULL DEFAULT 0,
    unqualified_receipt_count INT NOT NULL DEFAULT 0,
    return_count INT NOT NULL DEFAULT 0,
    finalized_settlement_count INT NOT NULL DEFAULT 0,
    quality_safety_fact_count INT NOT NULL DEFAULT 0,
    quality_safety_average DECIMAL(5,2) NULL,
    evaluation_comment VARCHAR(1000) NOT NULL,
    recommend_blacklist TINYINT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_performance_order (tenant_id, purchase_order_id, deleted_flag),
    UNIQUE KEY uk_sp_performance_code (tenant_id, evaluation_code, deleted_flag),
    KEY idx_sp_performance_partner (tenant_id, partner_id, status, period_end),
    CONSTRAINT fk_sp_performance_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_performance_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_performance_contract FOREIGN KEY (contract_id) REFERENCES ct_contract(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_performance_order FOREIGN KEY (purchase_order_id) REFERENCES mat_purchase_order(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_performance_scores CHECK (delivery_score BETWEEN 0 AND 100 AND quality_score BETWEEN 0 AND 100 AND service_score BETWEEN 0 AND 100 AND commercial_score BETWEEN 0 AND 100 AND total_score BETWEEN 0 AND 100),
    CONSTRAINT ck_sp_performance_status CHECK (status IN ('DRAFT','CONFIRMED')),
    CONSTRAINT ck_sp_performance_dates CHECK (period_end >= period_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商履约综合评价';

CREATE TABLE sp_blacklist_record (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    performance_evaluation_id BIGINT NOT NULL,
    partner_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    action_type VARCHAR(12) NOT NULL DEFAULT 'ADD',
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    submitted_by BIGINT NULL,
    submitted_at DATETIME NULL,
    reviewed_by BIGINT NULL,
    reviewed_at DATETIME NULL,
    review_comment VARCHAR(1000) NULL,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_blacklist_evaluation (tenant_id, performance_evaluation_id, deleted_flag),
    KEY idx_sp_blacklist_partner (tenant_id, partner_id, status),
    CONSTRAINT fk_sp_blacklist_evaluation FOREIGN KEY (performance_evaluation_id) REFERENCES sp_performance_evaluation(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_blacklist_partner FOREIGN KEY (partner_id) REFERENCES md_partner(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sp_blacklist_project FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sp_blacklist_action CHECK (action_type IN ('ADD')),
    CONSTRAINT ck_sp_blacklist_status CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商黑名单审批记录';

INSERT IGNORE INTO sys_menu(id,tenant_id,parent_id,menu_name,menu_type,path,component,perms,icon,order_num,status,visible) VALUES
(1104,0,2,'供应商招采履约','MENU','supplier-sourcing','supplier-sourcing/index','supplier:sourcing:query','team',10,'ENABLE',1),
(1105,0,1104,'维护询价招标','BUTTON',NULL,NULL,'supplier:sourcing:maintain',NULL,1,'ENABLE',1),
(1106,0,1104,'维护供应商报价','BUTTON',NULL,NULL,'supplier:sourcing:quote',NULL,2,'ENABLE',1),
(1107,0,1104,'执行比价评审','BUTTON',NULL,NULL,'supplier:sourcing:evaluate',NULL,3,'ENABLE',1),
(1108,0,1104,'执行定标与合同关联','BUTTON',NULL,NULL,'supplier:sourcing:award',NULL,4,'ENABLE',1),
(1109,0,1104,'确认履约评价','BUTTON',NULL,NULL,'supplier:performance:evaluate',NULL,5,'ENABLE',1),
(1110,0,1104,'审核供应商黑名单','BUTTON',NULL,NULL,'supplier:blacklist:review',NULL,6,'ENABLE',1);

INSERT IGNORE INTO sys_role_menu(id,role_id,menu_id)
SELECT 189000000+r.id*10000+m.id,r.id,m.id
FROM sys_role r JOIN sys_menu m ON m.id BETWEEN 1104 AND 1110
WHERE r.role_code IN ('SUPER_ADMIN','ADMIN','PROJECT_MANAGER','PURCHASE_MANAGER','COST_MANAGER','AUDITOR') AND r.deleted_flag=0;

SET FOREIGN_KEY_CHECKS = 1;
