-- 第51条主线：为已执行的 V213/V214 新表补齐字段注释，不修改历史迁移校验和。

ALTER TABLE cost_subject_mapping_version
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN version_code VARCHAR(64) NOT NULL COMMENT '映射版本编码',
    MODIFY COLUMN version_name VARCHAR(200) NOT NULL COMMENT '映射版本名称',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态',
    MODIFY COLUMN effective_date DATE NULL COMMENT '生效日期',
    MODIFY COLUMN approval_instance_id BIGINT NULL COMMENT '审批实例ID',
    MODIFY COLUMN activated_by BIGINT NULL COMMENT '启用人ID',
    MODIFY COLUMN activated_at DATETIME NULL COMMENT '启用时间',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注';

ALTER TABLE cost_subject_mapping_item
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN mapping_version_id BIGINT NOT NULL COMMENT '映射版本ID',
    MODIFY COLUMN source_subject_id BIGINT NOT NULL COMMENT '历史来源科目ID',
    MODIFY COLUMN target_group_code VARCHAR(64) NOT NULL COMMENT '目标科目组编码',
    MODIFY COLUMN target_subject_id BIGINT NULL COMMENT '目标科目ID',
    MODIFY COLUMN historical_display_name VARCHAR(200) NOT NULL COMMENT '历史显示名称',
    MODIFY COLUMN mapping_reason VARCHAR(500) NULL COMMENT '映射原因',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE cost_subject_assignment_rule
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN mapping_version_id BIGINT NOT NULL COMMENT '映射版本ID',
    MODIFY COLUMN rule_code VARCHAR(64) NOT NULL COMMENT '规则编码',
    MODIFY COLUMN source_type VARCHAR(64) NOT NULL COMMENT '业务来源类型',
    MODIFY COLUMN business_category VARCHAR(64) NOT NULL DEFAULT '*' COMMENT '业务分类',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '项目ID',
    MODIFY COLUMN cost_subject_id BIGINT NOT NULL COMMENT '成本科目ID',
    MODIFY COLUMN priority INT NOT NULL DEFAULT 100 COMMENT '匹配优先级',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '规则状态',
    MODIFY COLUMN effective_from DATE NOT NULL COMMENT '生效开始日期',
    MODIFY COLUMN effective_to DATE NULL COMMENT '生效结束日期',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注';

ALTER TABLE project_cost_subject_scope
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN cost_subject_id BIGINT NOT NULL COMMENT '成本科目ID',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN effective_from DATE NOT NULL COMMENT '生效开始日期',
    MODIFY COLUMN effective_to DATE NULL COMMENT '生效结束日期',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注';

ALTER TABLE bid_cost_target_transfer
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN bid_cost_id BIGINT NOT NULL COMMENT '投标成本ID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN target_id BIGINT NOT NULL COMMENT '目标成本版本ID',
    MODIFY COLUMN mapping_version_id BIGINT NOT NULL COMMENT '映射版本ID',
    MODIFY COLUMN transfer_code VARCHAR(64) NOT NULL COMMENT '转入单号',
    MODIFY COLUMN idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    MODIFY COLUMN total_amount DECIMAL(18,2) NOT NULL COMMENT '转入总额',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'POSTED' COMMENT '事实状态',
    MODIFY COLUMN approval_instance_id BIGINT NOT NULL COMMENT '审批实例ID',
    MODIFY COLUMN reversal_of_id BIGINT NULL COMMENT '被冲销事实ID',
    MODIFY COLUMN posted_by BIGINT NOT NULL COMMENT '记账人ID',
    MODIFY COLUMN posted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记账时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注';

ALTER TABLE bid_cost_target_transfer_line
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN transfer_id BIGINT NOT NULL COMMENT '转入事实ID',
    MODIFY COLUMN source_cost_item_id BIGINT NOT NULL COMMENT '来源成本明细ID',
    MODIFY COLUMN source_subject_id BIGINT NOT NULL COMMENT '来源成本科目ID',
    MODIFY COLUMN target_subject_id BIGINT NOT NULL COMMENT '目标成本科目ID',
    MODIFY COLUMN amount DECIMAL(18,2) NOT NULL COMMENT '转入金额',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE finance_cost_allocation_batch
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN batch_code VARCHAR(64) NOT NULL COMMENT '分摊批次号',
    MODIFY COLUMN source_type VARCHAR(32) NOT NULL COMMENT '来源类型',
    MODIFY COLUMN source_id BIGINT NOT NULL COMMENT '来源单据ID',
    MODIFY COLUMN source_amount DECIMAL(18,2) NOT NULL COMMENT '待分摊金额',
    MODIFY COLUMN allocation_basis VARCHAR(32) NOT NULL COMMENT '分摊依据',
    MODIFY COLUMN accounting_period CHAR(7) NOT NULL COMMENT '会计期间',
    MODIFY COLUMN cost_subject_id BIGINT NOT NULL COMMENT '财务费用成本科目ID',
    MODIFY COLUMN idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'POSTED' COMMENT '事实状态',
    MODIFY COLUMN approval_instance_id BIGINT NOT NULL COMMENT '审批实例ID',
    MODIFY COLUMN reversal_of_id BIGINT NULL COMMENT '被冲销批次ID',
    MODIFY COLUMN posted_by BIGINT NOT NULL COMMENT '记账人ID',
    MODIFY COLUMN posted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记账时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注';

ALTER TABLE finance_cost_allocation_line
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN batch_id BIGINT NOT NULL COMMENT '分摊批次ID',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN basis_value DECIMAL(18,6) NOT NULL COMMENT '分摊基数',
    MODIFY COLUMN allocated_amount DECIMAL(18,2) NOT NULL COMMENT '分摊金额',
    MODIFY COLUMN cost_item_id BIGINT NULL COMMENT '生成成本明细ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE cost_subject_legacy_cleanup_audit
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    MODIFY COLUMN legacy_subject_id BIGINT NOT NULL COMMENT '旧成本科目ID',
    MODIFY COLUMN legacy_subject_code VARCHAR(64) NOT NULL COMMENT '旧成本科目编码',
    MODIFY COLUMN legacy_subject_name VARCHAR(200) NOT NULL COMMENT '旧成本科目名称',
    MODIFY COLUMN replacement_subject_id BIGINT NOT NULL COMMENT '替代成本科目ID',
    MODIFY COLUMN replacement_subject_code VARCHAR(64) NOT NULL COMMENT '替代成本科目编码',
    MODIFY COLUMN replacement_subject_name VARCHAR(200) NOT NULL COMMENT '替代成本科目名称',
    MODIFY COLUMN migration_reason VARCHAR(500) NOT NULL COMMENT '迁移原因',
    MODIFY COLUMN migrated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '迁移时间';
