-- V119: backfill alert domain for rows created before V118
UPDATE alert_log
SET alert_domain = CASE rule_type
    WHEN 'DYNAMIC_COST_EXCEEDS_TARGET' THEN 'COST'
    WHEN 'MATERIAL_EXCEEDS_BUDGET' THEN 'COST'
    WHEN 'SUBCONTRACT_EXCEEDS_CONTRACT' THEN 'COST'
    WHEN 'CONTRACT_OVERDUE' THEN 'CONTRACT'
    WHEN 'CONTRACT_EXPIRING' THEN 'CONTRACT'
    WHEN 'WARRANTY_EARLY_RELEASE' THEN 'CONTRACT'
    WHEN 'PAYMENT_EXCEEDS_RATIO' THEN 'PAYMENT'
    WHEN 'VARIATION_UNCONFIRMED' THEN 'VARIATION'
    WHEN 'PURCHASE_DELIVERY_OVERDUE' THEN 'PURCHASE'
    ELSE alert_domain
END
WHERE (alert_domain IS NULL OR alert_domain = '')
  AND rule_type IN (
      'DYNAMIC_COST_EXCEEDS_TARGET',
      'MATERIAL_EXCEEDS_BUDGET',
      'SUBCONTRACT_EXCEEDS_CONTRACT',
      'CONTRACT_OVERDUE',
      'CONTRACT_EXPIRING',
      'WARRANTY_EARLY_RELEASE',
      'PAYMENT_EXCEEDS_RATIO',
      'VARIATION_UNCONFIRMED',
      'PURCHASE_DELIVERY_OVERDUE'
  );
