-- V99: 总工程师最小技术域契约
-- H2

CREATE TABLE IF NOT EXISTS tech_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NOT NULL,
    item_type VARCHAR(50) NOT NULL,
    item_code VARCHAR(50) NOT NULL,
    item_title VARCHAR(200) NOT NULL,
    item_level VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    item_status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    discovered_at TIMESTAMP NULL,
    due_date TIMESTAMP NULL,
    closed_at TIMESTAMP NULL,
    responsible_user_id BIGINT NULL,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(500) NULL,
    CONSTRAINT uk_tech_item_code UNIQUE (tenant_id, item_code)
);

CREATE INDEX idx_tech_item_tenant_project ON tech_item (tenant_id, project_id);
CREATE INDEX idx_tech_item_tenant_type_status ON tech_item (tenant_id, item_type, item_status);
CREATE INDEX idx_tech_item_tenant_level_status ON tech_item (tenant_id, item_level, item_status);

INSERT INTO sys_menu (id, tenant_id, parent_id, menu_name, menu_type, path, component, perms, icon, order_num, status, visible)
VALUES (815, 0, 1, '总工程师驾驶舱', 'BUTTON', NULL, NULL, 'dashboard:chief-engineer:view', NULL, 9, 'ENABLE', 1);

INSERT INTO sys_role (id, tenant_id, role_code, role_name, role_type, status, data_scope, created_by, remark)
VALUES (9, 0, 'CHIEF_ENGINEER', '总工程师', 'BUSINESS', 'ENABLE', 'ALL', 1, '总工程师默认角色');

INSERT INTO sys_role_menu (id, role_id, menu_id)
VALUES (99001, 9, 1), (99002, 9, 803), (99003, 9, 815);

INSERT INTO tech_item
(id, tenant_id, project_id, item_type, item_code, item_title, item_level, item_status, discovered_at, due_date, closed_at, responsible_user_id, created_by, updated_by, deleted_flag, remark)
VALUES
(1, 0, 10001, 'TECH_REVIEW', 'TECH-DEMO-001', '施工组织设计复核', 'HIGH', 'PENDING', CURRENT_TIMESTAMP, DATEADD('DAY', 3, CURRENT_TIMESTAMP), NULL, 1, 1, 1, 0, 'chief-engineer demo seed'),
(2, 0, 10001, 'TECH_ISSUE', 'TECH-DEMO-002', '桩基专项方案问题闭环', 'URGENT', 'OPEN', CURRENT_TIMESTAMP, DATEADD('DAY', 1, CURRENT_TIMESTAMP), NULL, 1, 1, 1, 0, 'chief-engineer demo seed');
