CREATE TABLE IF NOT EXISTS receivable_adjustment(id BIGINT PRIMARY KEY,tenant_id BIGINT DEFAULT 0 NOT NULL,receivable_id BIGINT NOT NULL,adjustment_type VARCHAR(32) NOT NULL,amount DECIMAL(18,2) NOT NULL,reason VARCHAR(500) NOT NULL,idempotency_key VARCHAR(128) NOT NULL,status VARCHAR(32) NOT NULL,created_by BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT fk_receivable_adjustment_ar FOREIGN KEY(receivable_id) REFERENCES account_receivable(id));
CREATE UNIQUE INDEX IF NOT EXISTS uk_receivable_adjustment_key ON receivable_adjustment(tenant_id,idempotency_key);
CREATE TABLE IF NOT EXISTS collection_reversal(id BIGINT PRIMARY KEY,tenant_id BIGINT DEFAULT 0 NOT NULL,collection_id BIGINT NOT NULL,idempotency_key VARCHAR(128) NOT NULL,reason VARCHAR(500) NOT NULL,status VARCHAR(32) NOT NULL,created_by BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT fk_collection_reversal_record FOREIGN KEY(collection_id) REFERENCES collection_record(id));
CREATE UNIQUE INDEX IF NOT EXISTS uk_collection_reversal_key ON collection_reversal(tenant_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS uk_collection_reversal_record ON collection_reversal(tenant_id,collection_id);
CREATE TABLE IF NOT EXISTS collection_schedule(id BIGINT PRIMARY KEY,tenant_id BIGINT DEFAULT 0 NOT NULL,project_id BIGINT NOT NULL,contract_id BIGINT NOT NULL,receivable_id BIGINT,planned_date DATE NOT NULL,planned_amount DECIMAL(18,2) NOT NULL,collected_amount DECIMAL(18,2) DEFAULT 0 NOT NULL,reminder_days INT DEFAULT 7 NOT NULL,status VARCHAR(32) DEFAULT 'PLANNED' NOT NULL,note VARCHAR(500) NOT NULL,version INT DEFAULT 0 NOT NULL,created_by BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_by BIGINT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT fk_collection_schedule_project FOREIGN KEY(project_id) REFERENCES pm_project(id),CONSTRAINT fk_collection_schedule_contract FOREIGN KEY(contract_id) REFERENCES ct_contract(id),CONSTRAINT fk_collection_schedule_receivable FOREIGN KEY(receivable_id) REFERENCES account_receivable(id));
CREATE TABLE IF NOT EXISTS revenue_reconciliation_run(id BIGINT PRIMARY KEY,tenant_id BIGINT DEFAULT 0 NOT NULL,business_date DATE NOT NULL,status VARCHAR(32) NOT NULL,issue_count INT DEFAULT 0 NOT NULL,started_at TIMESTAMP NOT NULL,finished_at TIMESTAMP,created_by BIGINT);
CREATE UNIQUE INDEX IF NOT EXISTS uk_revenue_recon_day ON revenue_reconciliation_run(tenant_id,business_date);
CREATE TABLE IF NOT EXISTS revenue_reconciliation_issue(id BIGINT PRIMARY KEY,tenant_id BIGINT DEFAULT 0 NOT NULL,run_id BIGINT NOT NULL,dimension_type VARCHAR(64) NOT NULL,business_id BIGINT,issue_code VARCHAR(64) NOT NULL,expected_amount DECIMAL(18,2),actual_amount DECIMAL(18,2),status VARCHAR(32) DEFAULT 'OPEN' NOT NULL,detail VARCHAR(1000) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,CONSTRAINT fk_revenue_recon_issue_run FOREIGN KEY(run_id) REFERENCES revenue_reconciliation_run(id));
