ALTER TABLE mat_receipt
    ADD COLUMN IF NOT EXISTS receipt_mode VARCHAR(30) NOT NULL DEFAULT 'INVENTORY';

ALTER TABLE mat_stock
    ADD COLUMN IF NOT EXISTS inventory_value DECIMAL(18,2) NOT NULL DEFAULT 0;

ALTER TABLE mat_stock
    ADD COLUMN IF NOT EXISTS average_unit_cost DECIMAL(18,6) NOT NULL DEFAULT 0;

ALTER TABLE mat_stock_txn
    ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(18,6) NOT NULL DEFAULT 0;

ALTER TABLE mat_stock_txn
    ADD COLUMN IF NOT EXISTS amount DECIMAL(18,2) NOT NULL DEFAULT 0;
