spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cgc_pms_test?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:cgc}
    password: ${DB_PASSWORD:ENC(8TK7iL5rMvapLXkoMQ7rm8ngWpm8Pryn2/y9T0fv7sIraCAw9iiBJFICgqzEhSyE)}
    hikari:
      pool-name: CgcPmsHikariPool
      minimum-idle: 2
      maximum-pool-size: 10

  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 5000ms

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: true

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY:ENC(93qmaOL3j0Sfw0u0Juj/Iwvrv2a2waPK4Fnk6F37XWeBzNTdk7RerukazbN0G1a+)}
  secret-key: ${MINIO_SECRET_KEY:ENC(TpgnxaWPMxXdj8dlhB1QEiua+tAJUbLUWzD44JKKUXWW32TpIxTolhj1rYGoMc2+)}
  bucket: cgc-pms-test

jwt:
  secret: ${JWT_SECRET:ENC(EgW35Fy6JTLUkNtV9HYfsjMRg0O8D4kcOs/TmXwQCAJG7DwIf138Vp5+0V0MyRJlUZ5NAIUj/osChqroG4D4Sg8+5mcXurkd0yOy/uaO3xUbQxMl3mJlHWGdThupua+JgaUQNliDGm0pRdIohnMO1w==)}
  expiration: 86400000
  refresh-expiration: 604800000
  header: Authorization
  token-prefix: "Bearer "

cors:
  allowed-origins: "http://localhost:5173"

logging:
  level:
    root: INFO
    com.cgcpms: DEBUG
